//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 03:44:22 PM EDT 
//


package com.sandata.lab.data.model.dl.model;

import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.Adapter1;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.Date;


/**
 * <p>Java class for Application_Audit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application_Audit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Application_Audit_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Application_Session_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="User_Globally_Unique_Identifier" type="{}Computing_Globally_Unique_Identifier" />
 *       &lt;attribute name="Application_Privilege_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Audit_Host" type="{}Computing_Host" />
 *       &lt;attribute name="Data_Security_Compliance_Type_Name" type="{}Data_Security_Compliance_Type_Name" />
 *       &lt;attribute name="Data_Security_Classification_ID" type="{}Data_Security_Classification_ID" />
 *       &lt;attribute name="Application_Data_Structure_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Application_Data_Structure_Element_Value" type="{}Text_Property_Value_Long" />
 *       &lt;attribute name="Audit_Data_Structure_Read_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Audit_Data_Structure_Write_Indicator" type="{}Indicator" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application_Audit")
@OracleMetadata(
        packageName = "PKG_APP",
        insertMethod = "insertAppAudit",
        updateMethod = "updateAppAudit",
        deleteMethod = "deleteAppAudit",
        getMethod = "getAppAudit",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.AppAuditT",
        primaryKeys = {})
public class ApplicationAudit extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlAttribute(name = "Application_Audit_SK", required = true)
    @SerializedName("ApplicationAuditSK")
	@Mapping(getter = "getAppAuditSk", setter = "setAppAuditSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger applicationAuditSK;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 1)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(Adapter1.class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Application_Session_SK")
    @SerializedName("ApplicationSessionSK")
	@Mapping(getter = "getAppSessSk", setter = "setAppSessSk", type = "java.math.BigDecimal", index = 3)
    protected BigInteger applicationSessionSK;
    @XmlAttribute(name = "User_Globally_Unique_Identifier")
    @SerializedName("UserGloballyUniqueIdentifier")
	@Mapping(getter = "getUserGuid", setter = "setUserGuid", type = "String", index = 4)
    protected String userGloballyUniqueIdentifier;
    @XmlAttribute(name = "Application_Privilege_SK")
    @SerializedName("ApplicationPrivilegeSK")
	@Mapping(getter = "getAppPrivSk", setter = "setAppPrivSk", type = "java.math.BigDecimal", index = 5)
    protected BigInteger applicationPrivilegeSK;
    @XmlAttribute(name = "Audit_Host")
    @SerializedName("AuditHost")
	@Mapping(getter = "getAuditHost", setter = "setAuditHost", type = "String", index = 6)
    protected String auditHost;
    @XmlAttribute(name = "Data_Security_Compliance_Type_Name")
    @SerializedName("DataSecurityComplianceTypeName")
	@Mapping(getter = "getDataSecCompTypName", setter = "setDataSecCompTypName", type = "String", index = 7)
    protected DataSecurityComplianceTypeName dataSecurityComplianceTypeName;
    @XmlAttribute(name = "Data_Security_Classification_ID")
    @SerializedName("DataSecurityClassificationID")
	@Mapping(getter = "getDataSecClasId", setter = "setDataSecClasId", type = "String", index = 8)
    protected String dataSecurityClassificationID;
    @XmlAttribute(name = "Application_Data_Structure_SK")
    @SerializedName("ApplicationDataStructureSK")
	@Mapping(getter = "getAppDataStrucSk", setter = "setAppDataStrucSk", type = "java.math.BigDecimal", index = 9)
    protected BigInteger applicationDataStructureSK;
    @XmlAttribute(name = "Application_Data_Structure_Element_Value")
    @SerializedName("ApplicationDataStructureElementValue")
	@Mapping(getter = "getAppDataStrucEltVal", setter = "setAppDataStrucEltVal", type = "String", index = 10)
    protected String applicationDataStructureElementValue;
    @XmlAttribute(name = "Audit_Data_Structure_Read_Indicator")
    @SerializedName("AuditDataStructureReadIndicator")
	@Mapping(getter = "getAuditDataStrucReadInd", setter = "setAuditDataStrucReadInd", type = "java.math.BigDecimal", index = 11)
    protected Boolean auditDataStructureReadIndicator;
    @XmlAttribute(name = "Audit_Data_Structure_Write_Indicator")
    @SerializedName("AuditDataStructureWriteIndicator")
	@Mapping(getter = "getAuditDataStrucWriteInd", setter = "setAuditDataStrucWriteInd", type = "java.math.BigDecimal", index = 12)
    protected Boolean auditDataStructureWriteIndicator;

    /**
     * Gets the value of the applicationAuditSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationAuditSK() {
        return applicationAuditSK;
    }

    /**
     * Sets the value of the applicationAuditSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationAuditSK(BigInteger value) {
        this.applicationAuditSK = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the applicationSessionSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationSessionSK() {
        return applicationSessionSK;
    }

    /**
     * Sets the value of the applicationSessionSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationSessionSK(BigInteger value) {
        this.applicationSessionSK = value;
    }

    /**
     * Gets the value of the userGloballyUniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserGloballyUniqueIdentifier() {
        return userGloballyUniqueIdentifier;
    }

    /**
     * Sets the value of the userGloballyUniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserGloballyUniqueIdentifier(String value) {
        this.userGloballyUniqueIdentifier = value;
    }

    /**
     * Gets the value of the applicationPrivilegeSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationPrivilegeSK() {
        return applicationPrivilegeSK;
    }

    /**
     * Sets the value of the applicationPrivilegeSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationPrivilegeSK(BigInteger value) {
        this.applicationPrivilegeSK = value;
    }

    /**
     * Gets the value of the auditHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditHost() {
        return auditHost;
    }

    /**
     * Sets the value of the auditHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditHost(String value) {
        this.auditHost = value;
    }

    /**
     * Gets the value of the dataSecurityComplianceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link DataSecurityComplianceTypeName }
     *     
     */
    public DataSecurityComplianceTypeName getDataSecurityComplianceTypeName() {
        return dataSecurityComplianceTypeName;
    }

    /**
     * Sets the value of the dataSecurityComplianceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSecurityComplianceTypeName }
     *     
     */
    public void setDataSecurityComplianceTypeName(DataSecurityComplianceTypeName value) {
        this.dataSecurityComplianceTypeName = value;
    }

    /**
     * Gets the value of the dataSecurityClassificationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSecurityClassificationID() {
        return dataSecurityClassificationID;
    }

    /**
     * Sets the value of the dataSecurityClassificationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSecurityClassificationID(String value) {
        this.dataSecurityClassificationID = value;
    }

    /**
     * Gets the value of the applicationDataStructureSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicationDataStructureSK() {
        return applicationDataStructureSK;
    }

    /**
     * Sets the value of the applicationDataStructureSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicationDataStructureSK(BigInteger value) {
        this.applicationDataStructureSK = value;
    }

    /**
     * Gets the value of the applicationDataStructureElementValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationDataStructureElementValue() {
        return applicationDataStructureElementValue;
    }

    /**
     * Sets the value of the applicationDataStructureElementValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationDataStructureElementValue(String value) {
        this.applicationDataStructureElementValue = value;
    }

    /**
     * Gets the value of the auditDataStructureReadIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuditDataStructureReadIndicator() {
        return auditDataStructureReadIndicator;
    }

    /**
     * Sets the value of the auditDataStructureReadIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuditDataStructureReadIndicator(Boolean value) {
        this.auditDataStructureReadIndicator = value;
    }

    /**
     * Gets the value of the auditDataStructureWriteIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuditDataStructureWriteIndicator() {
        return auditDataStructureWriteIndicator;
    }

    /**
     * Sets the value of the auditDataStructureWriteIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuditDataStructureWriteIndicator(Boolean value) {
        this.auditDataStructureWriteIndicator = value;
    }

}
