//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 11:05:46 PM EDT 
//


package com.sandata.lab.data.model.dl.model;

import com.google.gson.annotations.SerializedName;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Billing_Frequency_Type_Name.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Billing_Frequency_Type_Name">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="50"/>
 *     &lt;enumeration value="WEEKLY"/>
 *     &lt;enumeration value="MONTHLY"/>
 *     &lt;enumeration value="DAILY"/>
 *     &lt;enumeration value="BI-WEEKLY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Billing_Frequency_Type_Name")
@XmlEnum
public enum BillingFrequencyTypeName {


    /**
     * Indicates that the billing process runs once a week
     * 
     */
    @SerializedName("WEEKLY")
    WEEKLY("WEEKLY"),

    /**
     * Indicates that the billing process runs once a month
     * 
     */
    @SerializedName("MONTHLY")
    MONTHLY("MONTHLY"),

    /**
     * Indicates that the billing process runs once a day
     * 
     */
    @SerializedName("DAILY")
    DAILY("DAILY"),

    /**
     * Indicates that the billing process runs every other week
     * 
     */
    @SerializedName("BI-WEEKLY")
    BI_WEEKLY("BI-WEEKLY");

    private final String value;

    BillingFrequencyTypeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BillingFrequencyTypeName fromValue(String v) {
        for (BillingFrequencyTypeName c: BillingFrequencyTypeName.values()) {
            if (c.value.equalsIgnoreCase(v)) {
                return c;
            }
        }
        return valueOf(v);
    }
}
