//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.17 at 05:14:59 PM EST
//


package com.sandata.lab.data.model.dl.model;

import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.base.BaseObject;

import java.math.BigInteger;
import java.util.Date;

/**
 * Date: 10/23/15
 * Time: 11:04 AM
 */

public class FindPayerSimpleResult extends BaseObject {

    private static final long serialVersionUID = 1L;

    @SerializedName("PayerSK")
    private BigInteger payerSK;

    @SerializedName("PayerID")
    private String payerId;

    @SerializedName("PayerName")
    private String payerName;

    @SerializedName("PayerTypeQualifier")
    private PayerTypeQualifier payerTypeQualifier;

    @SerializedName("PayerActiveIndicator")
    private Boolean payerActiveIndicator;

    @SerializedName("PayerTermDate")
    private Date payerTermDate;

    public String getPayerId() {
        return payerId;
    }

    public void setPayerId(String payerId) {
        this.payerId = payerId;
    }

    public BigInteger getPayerSK() {
        return payerSK;
    }

    public void setPayerSK(BigInteger payerSK) {
        this.payerSK = payerSK;
    }

    public String getPayerName() {
        return payerName;
    }

    public void setPayerName(String payerName) {
        this.payerName = payerName;
    }

    public PayerTypeQualifier getPayerTypeQualifier() {
        return payerTypeQualifier;
    }

    public void setPayerTypeQualifier(PayerTypeQualifier payerTypeQualifier) {
        this.payerTypeQualifier = payerTypeQualifier;
    }

    public Boolean getPayerActiveIndicator() {
        return payerActiveIndicator;
    }

    public void setPayerActiveIndicator(Boolean payerActiveIndicator) {
        this.payerActiveIndicator = payerActiveIndicator;
    }

    public Date getPayerTermDate() {
        return payerTermDate;
    }

    public void setPayerTermDate(Date payerTermDate) {
        this.payerTermDate = payerTermDate;
    }
}
