//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 11:05:46 PM EDT 
//


package com.sandata.lab.data.model.dl.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.Adapter1;
import com.sandata.lab.data.model.Adapter2;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import java.math.BigInteger;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Inventory of medications being taken by the patient
 * 
 * <p>Java class for Patient_Medication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient_Medication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Patient_Medication_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Effective_Timestamp" use="required" type="{}Record_Effective_Timestamp" />
 *       &lt;attribute name="Record_Termination_Timestamp" use="required" type="{}Record_Termination_Timestamp" />
 *       &lt;attribute name="Record_Created_By" type="{}Record_Created_By" />
 *       &lt;attribute name="Record_Updated_By" type="{}Record_Updated_By" />
 *       &lt;attribute name="Change_Reason_Memo" type="{}Change_Reason_Memo" />
 *       &lt;attribute name="Current_Record_Indicator" use="required" type="{}Current_Record_Indicator" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Patient_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Medication_Generic_Name" use="required" type="{}Medication_Generic_Name" />
 *       &lt;attribute name="Medication_Dosage_Strength_Name" type="{}Medication_Dosage_Strength_Name" />
 *       &lt;attribute name="Medication_Dosage_Form_Name" type="{}Medication_Dosage_Form_Name" />
 *       &lt;attribute name="Medication_Dosage_Frequency_Name" type="{}Medication_Dosage_Frequency_Name" />
 *       &lt;attribute name="Frequency_Type_Lookup_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Medication_Route_Name" type="{}Medication_Route_Name" />
 *       &lt;attribute name="Medication_Classification_Name" type="{}Medication_Classification_Name" />
 *       &lt;attribute name="Medication_Start_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Medication_End_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Medication_Rank">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AuthReimburse">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Medication_PRN_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Medication_PRN_Reason" type="{}Description_Short" />
 *       &lt;attribute name="Medication_RXCUI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Medication_Contraindication">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Medication_Comment" type="{}Comment_Long" />
 *       &lt;attribute name="Medication_Info_Sheet">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient_Medication")
@OracleMetadata(
        packageName = "PKG_PATIENT",
        insertMethod = "insertPtMed",
        updateMethod = "updatePtMed",
        deleteMethod = "deletePtMed",
        getMethod = "getPtMed",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.PtMedT",
        primaryKeys = {})
public class PatientMedication extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlAttribute(name = "Patient_Medication_SK", required = true)
    @SerializedName("PatientMedicationSK")
	@Mapping(getter = "getPtMedSk", setter = "setPtMedSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger patientMedicationSK;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 1)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Record_Effective_Timestamp", required = true)
    @SerializedName("RecordEffectiveTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecEffTmstp", setter = "setRecEffTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordEffectiveTimestamp;
    @XmlAttribute(name = "Record_Termination_Timestamp", required = true)
    @SerializedName("RecordTerminationTimestamp")
    @XmlJavaTypeAdapter(Adapter1.class)
	@Mapping(getter = "getRecTermTmstp", setter = "setRecTermTmstp", type = "java.sql.Timestamp", index = 4)
    protected Date recordTerminationTimestamp;
    @XmlAttribute(name = "Record_Created_By")
    @SerializedName("RecordCreatedBy")
	@Mapping(getter = "getRecCreatedBy", setter = "setRecCreatedBy", type = "String", index = 5)
    protected String recordCreatedBy;
    @XmlAttribute(name = "Record_Updated_By")
    @SerializedName("RecordUpdatedBy")
	@Mapping(getter = "getRecUpdatedBy", setter = "setRecUpdatedBy", type = "String", index = 6)
    protected String recordUpdatedBy;
    @XmlAttribute(name = "Change_Reason_Memo")
    @SerializedName("ChangeReasonMemo")
	@Mapping(getter = "getChangeReasonMemo", setter = "setChangeReasonMemo", type = "String", index = 7)
    protected String changeReasonMemo;
    @XmlAttribute(name = "Current_Record_Indicator", required = true)
    @SerializedName("CurrentRecordIndicator")
	@Mapping(getter = "getCurrRecInd", setter = "setCurrRecInd", type = "java.math.BigDecimal", index = 8)
    protected boolean currentRecordIndicator;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 9)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Patient_ID", required = true)
    @SerializedName("PatientID")
	@Mapping(getter = "getPtId", setter = "setPtId", type = "String", index = 10)
    protected String patientID;
    @XmlAttribute(name = "Business_Entity_ID", required = true)
    @SerializedName("BusinessEntityID")
	@Mapping(getter = "getBeId", setter = "setBeId", type = "String", index = 11)
    protected String businessEntityID;
    @XmlAttribute(name = "Medication_Generic_Name", required = true)
    @SerializedName("MedicationGenericName")
	@Mapping(getter = "getMedGenericName", setter = "setMedGenericName", type = "String", index = 12)
    protected String medicationGenericName;
    @XmlAttribute(name = "Medication_Dosage_Strength_Name")
    @SerializedName("MedicationDosageStrengthName")
	@Mapping(getter = "getMedDosageStrgName", setter = "setMedDosageStrgName", type = "String", index = 13)
    protected String medicationDosageStrengthName;
    @XmlAttribute(name = "Medication_Dosage_Form_Name")
    @SerializedName("MedicationDosageFormName")
	@Mapping(getter = "getMedDosageFormName", setter = "setMedDosageFormName", type = "String", index = 14)
    protected String medicationDosageFormName;
    @XmlAttribute(name = "Medication_Dosage_Frequency_Name")
    @SerializedName("MedicationDosageFrequencyName")
	@Mapping(getter = "getMedDosageFreqName", setter = "setMedDosageFreqName", type = "String", index = 15)
    protected String medicationDosageFrequencyName;
    @XmlAttribute(name = "Frequency_Type_Lookup_SK")
    @SerializedName("FrequencyTypeLookupSK")
	@Mapping(getter = "getFreqTypLkupSk", setter = "setFreqTypLkupSk", type = "java.math.BigDecimal", index = 16)
    protected BigInteger frequencyTypeLookupSK;
    @XmlAttribute(name = "Medication_Route_Name")
    @SerializedName("MedicationRouteName")
	@Mapping(getter = "getMedRouteName", setter = "setMedRouteName", type = "String", index = 17)
    protected String medicationRouteName;
    @XmlAttribute(name = "Medication_Classification_Name")
    @SerializedName("MedicationClassificationName")
	@Mapping(getter = "getMedClasName", setter = "setMedClasName", type = "String", index = 18)
    protected String medicationClassificationName;
    @XmlAttribute(name = "Medication_Start_Date")
    @SerializedName("MedicationStartDate")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter2.class)
    @XmlSchemaType(name = "date")
	@Mapping(getter = "getMedStartDate", setter = "setMedStartDate", type = "java.sql.Timestamp", index = 19)
    protected Date medicationStartDate;
    @XmlAttribute(name = "Medication_End_Date")
    @SerializedName("MedicationEndDate")
    @XmlJavaTypeAdapter(Adapter2.class)
    @XmlSchemaType(name = "date")
	@Mapping(getter = "getMedEndDate", setter = "setMedEndDate", type = "java.sql.Timestamp", index = 20)
    protected Date medicationEndDate;
    @XmlAttribute(name = "Medication_Rank")
    @SerializedName("MedicationRank")
	@Mapping(getter = "getMedRank", setter = "setMedRank", type = "String", index = 21)
    protected String medicationRank;
    @XmlAttribute(name = "AuthReimburse")
    @SerializedName("AuthReimburse")
	@Mapping(getter = "getAuthreimburse", setter = "setAuthreimburse", type = "String", index = 22)
    protected String authReimburse;
    @XmlAttribute(name = "Medication_PRN_Indicator")
    @SerializedName("MedicationPRNIndicator")
	@Mapping(getter = "getMedPrnInd", setter = "setMedPrnInd", type = "java.math.BigDecimal", index = 23)
    protected Boolean medicationPRNIndicator;
    @XmlAttribute(name = "Medication_PRN_Reason")
    @SerializedName("MedicationPRNReason")
	@Mapping(getter = "getMedPrnReason", setter = "setMedPrnReason", type = "String", index = 24)
    protected String medicationPRNReason;
    @XmlAttribute(name = "Medication_RXCUI")
    @SerializedName("MedicationRXCUI")
	@Mapping(getter = "getMedRxcui", setter = "setMedRxcui", type = "String", index = 25)
    protected String medicationRXCUI;
    @XmlAttribute(name = "Medication_Contraindication")
    @SerializedName("MedicationContraindication")
	@Mapping(getter = "getMedContraindication", setter = "setMedContraindication", type = "String", index = 26)
    protected String medicationContraindication;
    @XmlAttribute(name = "Medication_Comment")
    @SerializedName("MedicationComment")
	@Mapping(getter = "getMedComment", setter = "setMedComment", type = "String", index = 27)
    protected String medicationComment;
    @XmlAttribute(name = "Medication_Info_Sheet")
    @SerializedName("MedicationInfoSheet")
	@Mapping(getter = "getMedInfoSheet", setter = "setMedInfoSheet", type = "oracle.sql.BLOB", index = 28)
    protected byte[] medicationInfoSheet;

    /**
     * Gets the value of the patientMedicationSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPatientMedicationSK() {
        return patientMedicationSK;
    }

    /**
     * Sets the value of the patientMedicationSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPatientMedicationSK(BigInteger value) {
        this.patientMedicationSK = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the recordEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordEffectiveTimestamp() {
        return recordEffectiveTimestamp;
    }

    /**
     * Sets the value of the recordEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordEffectiveTimestamp(Date value) {
        this.recordEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the recordTerminationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordTerminationTimestamp() {
        return recordTerminationTimestamp;
    }

    /**
     * Sets the value of the recordTerminationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordTerminationTimestamp(Date value) {
        this.recordTerminationTimestamp = value;
    }

    /**
     * Gets the value of the recordCreatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreatedBy() {
        return recordCreatedBy;
    }

    /**
     * Sets the value of the recordCreatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreatedBy(String value) {
        this.recordCreatedBy = value;
    }

    /**
     * Gets the value of the recordUpdatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdatedBy() {
        return recordUpdatedBy;
    }

    /**
     * Sets the value of the recordUpdatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdatedBy(String value) {
        this.recordUpdatedBy = value;
    }

    /**
     * Gets the value of the changeReasonMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeReasonMemo() {
        return changeReasonMemo;
    }

    /**
     * Sets the value of the changeReasonMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeReasonMemo(String value) {
        this.changeReasonMemo = value;
    }

    /**
     * Gets the value of the currentRecordIndicator property.
     * 
     */
    public boolean isCurrentRecordIndicator() {
        return currentRecordIndicator;
    }

    /**
     * Sets the value of the currentRecordIndicator property.
     * 
     */
    public void setCurrentRecordIndicator(boolean value) {
        this.currentRecordIndicator = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the businessEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityID() {
        return businessEntityID;
    }

    /**
     * Sets the value of the businessEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityID(String value) {
        this.businessEntityID = value;
    }

    /**
     * Gets the value of the medicationGenericName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationGenericName() {
        return medicationGenericName;
    }

    /**
     * Sets the value of the medicationGenericName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationGenericName(String value) {
        this.medicationGenericName = value;
    }

    /**
     * Gets the value of the medicationDosageStrengthName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationDosageStrengthName() {
        return medicationDosageStrengthName;
    }

    /**
     * Sets the value of the medicationDosageStrengthName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationDosageStrengthName(String value) {
        this.medicationDosageStrengthName = value;
    }

    /**
     * Gets the value of the medicationDosageFormName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationDosageFormName() {
        return medicationDosageFormName;
    }

    /**
     * Sets the value of the medicationDosageFormName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationDosageFormName(String value) {
        this.medicationDosageFormName = value;
    }

    /**
     * Gets the value of the medicationDosageFrequencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationDosageFrequencyName() {
        return medicationDosageFrequencyName;
    }

    /**
     * Sets the value of the medicationDosageFrequencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationDosageFrequencyName(String value) {
        this.medicationDosageFrequencyName = value;
    }

    /**
     * Gets the value of the frequencyTypeLookupSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFrequencyTypeLookupSK() {
        return frequencyTypeLookupSK;
    }

    /**
     * Sets the value of the frequencyTypeLookupSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFrequencyTypeLookupSK(BigInteger value) {
        this.frequencyTypeLookupSK = value;
    }

    /**
     * Gets the value of the medicationRouteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationRouteName() {
        return medicationRouteName;
    }

    /**
     * Sets the value of the medicationRouteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationRouteName(String value) {
        this.medicationRouteName = value;
    }

    /**
     * Gets the value of the medicationClassificationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationClassificationName() {
        return medicationClassificationName;
    }

    /**
     * Sets the value of the medicationClassificationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationClassificationName(String value) {
        this.medicationClassificationName = value;
    }

    /**
     * Gets the value of the medicationStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getMedicationStartDate() {
        return medicationStartDate;
    }

    /**
     * Sets the value of the medicationStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationStartDate(Date value) {
        this.medicationStartDate = value;
    }

    /**
     * Gets the value of the medicationEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getMedicationEndDate() {
        return medicationEndDate;
    }

    /**
     * Sets the value of the medicationEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationEndDate(Date value) {
        this.medicationEndDate = value;
    }

    /**
     * Gets the value of the medicationRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationRank() {
        return medicationRank;
    }

    /**
     * Sets the value of the medicationRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationRank(String value) {
        this.medicationRank = value;
    }

    /**
     * Gets the value of the authReimburse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthReimburse() {
        return authReimburse;
    }

    /**
     * Sets the value of the authReimburse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthReimburse(String value) {
        this.authReimburse = value;
    }

    /**
     * Gets the value of the medicationPRNIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMedicationPRNIndicator() {
        return medicationPRNIndicator;
    }

    /**
     * Sets the value of the medicationPRNIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMedicationPRNIndicator(Boolean value) {
        this.medicationPRNIndicator = value;
    }

    /**
     * Gets the value of the medicationPRNReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationPRNReason() {
        return medicationPRNReason;
    }

    /**
     * Sets the value of the medicationPRNReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationPRNReason(String value) {
        this.medicationPRNReason = value;
    }

    /**
     * Gets the value of the medicationRXCUI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationRXCUI() {
        return medicationRXCUI;
    }

    /**
     * Sets the value of the medicationRXCUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationRXCUI(String value) {
        this.medicationRXCUI = value;
    }

    /**
     * Gets the value of the medicationContraindication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationContraindication() {
        return medicationContraindication;
    }

    /**
     * Sets the value of the medicationContraindication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationContraindication(String value) {
        this.medicationContraindication = value;
    }

    /**
     * Gets the value of the medicationComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicationComment() {
        return medicationComment;
    }

    /**
     * Sets the value of the medicationComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicationComment(String value) {
        this.medicationComment = value;
    }

    /**
     * Gets the value of the medicationInfoSheet property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMedicationInfoSheet() {
        return medicationInfoSheet;
    }

    /**
     * Sets the value of the medicationInfoSheet property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMedicationInfoSheet(byte[] value) {
        this.medicationInfoSheet = value;
    }

}
