//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 11:05:46 PM EDT 
//


package com.sandata.lab.data.model.dl.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.Adapter1;
import com.sandata.lab.data.model.Adapter2;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Details the various services, activities and tasks that need to be peformed during visits to a patient
 * 
 * <p>Java class for Plan_Of_Care complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Plan_Of_Care">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Plan_Of_Care_Service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Plan_Of_Care_Activity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Schedule_Event" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Plan_Of_Care_Task_List" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Plan_Of_Care_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Plan_Of_Care_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Effective_Timestamp" use="required" type="{}Record_Effective_Timestamp" />
 *       &lt;attribute name="Record_Termination_Timestamp" use="required" type="{}Record_Termination_Timestamp" />
 *       &lt;attribute name="Current_Record_Indicator" use="required" type="{}Current_Record_Indicator" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Patient_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Authorization_ID" type="{}ID" />
 *       &lt;attribute name="Frequency_Type_Lookup_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Plan_Of_Care_Start_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Plan_Of_Care_End_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Plan_Of_Treatment_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Days_Per_Week">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Plan_Of_Care_Day_1_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_2_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_3_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_4_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_5_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_6_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Day_7_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Plan_Of_Care_Hours_Per_Day">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;totalDigits value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plan_Of_Care", propOrder = {
    "planOfCareService",
    "planOfCareActivity",
    "scheduleEvent",
    "planOfCareTaskList"
})
@OracleMetadata(
        packageName = "PKG_POC",
        insertMethod = "insertPoc",
        updateMethod = "updatePoc",
        deleteMethod = "deletePoc",
        getMethod = "getPoc",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.PocT",
        primaryKeys = {})
public class PlanOfCare extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlElement(name = "Plan_Of_Care_Service")
    @SerializedName("PlanOfCareService")
    protected List<PlanOfCareService> planOfCareService;
    @XmlElement(name = "Plan_Of_Care_Activity")
    @SerializedName("PlanOfCareActivity")
    protected List<PlanOfCareActivity> planOfCareActivity;
    @XmlElement(name = "Schedule_Event")
    @SerializedName("ScheduleEvent")
    protected List<ScheduleEvent> scheduleEvent;
    @XmlElement(name = "Plan_Of_Care_Task_List")
    @SerializedName("PlanOfCareTaskList")
    protected List<PlanOfCareTaskList> planOfCareTaskList;
    @XmlAttribute(name = "Plan_Of_Care_SK", required = true)
    @SerializedName("PlanOfCareSK")
	@Mapping(getter = "getPocSk", setter = "setPocSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger planOfCareSK;
    @XmlAttribute(name = "Plan_Of_Care_ID", required = true)
    @SerializedName("PlanOfCareID")
	@Mapping(getter = "getPocId", setter = "setPocId", type = "String", index = 1)
    protected String planOfCareID;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Record_Effective_Timestamp", required = true)
    @SerializedName("RecordEffectiveTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecEffTmstp", setter = "setRecEffTmstp", type = "java.sql.Timestamp", index = 4)
    protected Date recordEffectiveTimestamp;
    @XmlAttribute(name = "Record_Termination_Timestamp", required = true)
    @SerializedName("RecordTerminationTimestamp")
    @XmlJavaTypeAdapter(Adapter1.class)
	@Mapping(getter = "getRecTermTmstp", setter = "setRecTermTmstp", type = "java.sql.Timestamp", index = 5)
    protected Date recordTerminationTimestamp;
    @XmlAttribute(name = "Current_Record_Indicator", required = true)
    @SerializedName("CurrentRecordIndicator")
	@Mapping(getter = "getCurrRecInd", setter = "setCurrRecInd", type = "java.math.BigDecimal", index = 6)
    protected boolean currentRecordIndicator;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 7)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Business_Entity_ID", required = true)
    @SerializedName("BusinessEntityID")
	@Mapping(getter = "getBeId", setter = "setBeId", type = "String", index = 8)
    protected String businessEntityID;
    @XmlAttribute(name = "Patient_ID", required = true)
    @SerializedName("PatientID")
	@Mapping(getter = "getPtId", setter = "setPtId", type = "String", index = 9)
    protected String patientID;
    @XmlAttribute(name = "Authorization_ID")
    @SerializedName("AuthorizationID")
	@Mapping(getter = "getAuthId", setter = "setAuthId", type = "String", index = 10)
    protected String authorizationID;
    @XmlAttribute(name = "Frequency_Type_Lookup_SK")
    @SerializedName("FrequencyTypeLookupSK")
	@Mapping(getter = "getFreqTypLkupSk", setter = "setFreqTypLkupSk", type = "java.math.BigDecimal", index = 11)
    protected BigInteger frequencyTypeLookupSK;
    @XmlAttribute(name = "Plan_Of_Care_Start_Date")
    @SerializedName("PlanOfCareStartDate")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter2.class)
    @XmlSchemaType(name = "date")
	@Mapping(getter = "getPocStartDate", setter = "setPocStartDate", type = "java.sql.Timestamp", index = 12)
    protected Date planOfCareStartDate;
    @XmlAttribute(name = "Plan_Of_Care_End_Date")
    @SerializedName("PlanOfCareEndDate")
    @XmlJavaTypeAdapter(Adapter2.class)
    @XmlSchemaType(name = "date")
	@Mapping(getter = "getPocEndDate", setter = "setPocEndDate", type = "java.sql.Timestamp", index = 13)
    protected Date planOfCareEndDate;
    @XmlAttribute(name = "Plan_Of_Treatment_Indicator")
    @SerializedName("PlanOfTreatmentIndicator")
	@Mapping(getter = "getPlanOfTreatInd", setter = "setPlanOfTreatInd", type = "java.math.BigDecimal", index = 14)
    protected Boolean planOfTreatmentIndicator;
    @XmlAttribute(name = "Plan_Of_Care_Days_Per_Week")
    @SerializedName("PlanOfCareDaysPerWeek")
	@Mapping(getter = "getPocDaysPerWeek", setter = "setPocDaysPerWeek", type = "java.math.BigDecimal", index = 15)
    protected BigDecimal planOfCareDaysPerWeek;
    @XmlAttribute(name = "Plan_Of_Care_Day_1_Indicator")
    @SerializedName("PlanOfCareDay1Indicator")
	@Mapping(getter = "getPocDay1Ind", setter = "setPocDay1Ind", type = "java.math.BigDecimal", index = 16)
    protected Boolean planOfCareDay1Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_2_Indicator")
    @SerializedName("PlanOfCareDay2Indicator")
	@Mapping(getter = "getPocDay2Ind", setter = "setPocDay2Ind", type = "java.math.BigDecimal", index = 17)
    protected Boolean planOfCareDay2Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_3_Indicator")
    @SerializedName("PlanOfCareDay3Indicator")
	@Mapping(getter = "getPocDay3Ind", setter = "setPocDay3Ind", type = "java.math.BigDecimal", index = 18)
    protected Boolean planOfCareDay3Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_4_Indicator")
    @SerializedName("PlanOfCareDay4Indicator")
	@Mapping(getter = "getPocDay4Ind", setter = "setPocDay4Ind", type = "java.math.BigDecimal", index = 19)
    protected Boolean planOfCareDay4Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_5_Indicator")
    @SerializedName("PlanOfCareDay5Indicator")
	@Mapping(getter = "getPocDay5Ind", setter = "setPocDay5Ind", type = "java.math.BigDecimal", index = 20)
    protected Boolean planOfCareDay5Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_6_Indicator")
    @SerializedName("PlanOfCareDay6Indicator")
	@Mapping(getter = "getPocDay6Ind", setter = "setPocDay6Ind", type = "java.math.BigDecimal", index = 21)
    protected Boolean planOfCareDay6Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Day_7_Indicator")
    @SerializedName("PlanOfCareDay7Indicator")
	@Mapping(getter = "getPocDay7Ind", setter = "setPocDay7Ind", type = "java.math.BigDecimal", index = 22)
    protected Boolean planOfCareDay7Indicator;
    @XmlAttribute(name = "Plan_Of_Care_Hours_Per_Day")
    @SerializedName("PlanOfCareHoursPerDay")
	@Mapping(getter = "getPocHrsPerDay", setter = "setPocHrsPerDay", type = "java.math.BigDecimal", index = 23)
    protected BigDecimal planOfCareHoursPerDay;

    /**
     * Gets the value of the planOfCareService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planOfCareService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanOfCareService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanOfCareService }
     * 
     * 
     */
    public List<PlanOfCareService> getPlanOfCareService() {
        if (planOfCareService == null) {
            planOfCareService = new ArrayList<PlanOfCareService>();
        }
        return this.planOfCareService;
    }

    /**
     * Gets the value of the planOfCareActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planOfCareActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanOfCareActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanOfCareActivity }
     * 
     * 
     */
    public List<PlanOfCareActivity> getPlanOfCareActivity() {
        if (planOfCareActivity == null) {
            planOfCareActivity = new ArrayList<PlanOfCareActivity>();
        }
        return this.planOfCareActivity;
    }

    /**
     * Gets the value of the scheduleEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduleEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduleEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduleEvent }
     * 
     * 
     */
    public List<ScheduleEvent> getScheduleEvent() {
        if (scheduleEvent == null) {
            scheduleEvent = new ArrayList<ScheduleEvent>();
        }
        return this.scheduleEvent;
    }

    /**
     * Gets the value of the planOfCareTaskList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planOfCareTaskList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanOfCareTaskList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanOfCareTaskList }
     * 
     * 
     */
    public List<PlanOfCareTaskList> getPlanOfCareTaskList() {
        if (planOfCareTaskList == null) {
            planOfCareTaskList = new ArrayList<PlanOfCareTaskList>();
        }
        return this.planOfCareTaskList;
    }

    /**
     * Gets the value of the planOfCareSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanOfCareSK() {
        return planOfCareSK;
    }

    /**
     * Sets the value of the planOfCareSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanOfCareSK(BigInteger value) {
        this.planOfCareSK = value;
    }

    /**
     * Gets the value of the planOfCareID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanOfCareID() {
        return planOfCareID;
    }

    /**
     * Sets the value of the planOfCareID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanOfCareID(String value) {
        this.planOfCareID = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the recordEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordEffectiveTimestamp() {
        return recordEffectiveTimestamp;
    }

    /**
     * Sets the value of the recordEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordEffectiveTimestamp(Date value) {
        this.recordEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the recordTerminationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordTerminationTimestamp() {
        return recordTerminationTimestamp;
    }

    /**
     * Sets the value of the recordTerminationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordTerminationTimestamp(Date value) {
        this.recordTerminationTimestamp = value;
    }

    /**
     * Gets the value of the currentRecordIndicator property.
     * 
     */
    public boolean isCurrentRecordIndicator() {
        return currentRecordIndicator;
    }

    /**
     * Sets the value of the currentRecordIndicator property.
     * 
     */
    public void setCurrentRecordIndicator(boolean value) {
        this.currentRecordIndicator = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the businessEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityID() {
        return businessEntityID;
    }

    /**
     * Sets the value of the businessEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityID(String value) {
        this.businessEntityID = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the authorizationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationID() {
        return authorizationID;
    }

    /**
     * Sets the value of the authorizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationID(String value) {
        this.authorizationID = value;
    }

    /**
     * Gets the value of the frequencyTypeLookupSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFrequencyTypeLookupSK() {
        return frequencyTypeLookupSK;
    }

    /**
     * Sets the value of the frequencyTypeLookupSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFrequencyTypeLookupSK(BigInteger value) {
        this.frequencyTypeLookupSK = value;
    }

    /**
     * Gets the value of the planOfCareStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPlanOfCareStartDate() {
        return planOfCareStartDate;
    }

    /**
     * Sets the value of the planOfCareStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanOfCareStartDate(Date value) {
        this.planOfCareStartDate = value;
    }

    /**
     * Gets the value of the planOfCareEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPlanOfCareEndDate() {
        return planOfCareEndDate;
    }

    /**
     * Sets the value of the planOfCareEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanOfCareEndDate(Date value) {
        this.planOfCareEndDate = value;
    }

    /**
     * Gets the value of the planOfTreatmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfTreatmentIndicator() {
        return planOfTreatmentIndicator;
    }

    /**
     * Sets the value of the planOfTreatmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfTreatmentIndicator(Boolean value) {
        this.planOfTreatmentIndicator = value;
    }

    /**
     * Gets the value of the planOfCareDaysPerWeek property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPlanOfCareDaysPerWeek() {
        return planOfCareDaysPerWeek;
    }

    /**
     * Sets the value of the planOfCareDaysPerWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPlanOfCareDaysPerWeek(BigDecimal value) {
        this.planOfCareDaysPerWeek = value;
    }

    /**
     * Gets the value of the planOfCareDay1Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay1Indicator() {
        return planOfCareDay1Indicator;
    }

    /**
     * Sets the value of the planOfCareDay1Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay1Indicator(Boolean value) {
        this.planOfCareDay1Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay2Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay2Indicator() {
        return planOfCareDay2Indicator;
    }

    /**
     * Sets the value of the planOfCareDay2Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay2Indicator(Boolean value) {
        this.planOfCareDay2Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay3Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay3Indicator() {
        return planOfCareDay3Indicator;
    }

    /**
     * Sets the value of the planOfCareDay3Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay3Indicator(Boolean value) {
        this.planOfCareDay3Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay4Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay4Indicator() {
        return planOfCareDay4Indicator;
    }

    /**
     * Sets the value of the planOfCareDay4Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay4Indicator(Boolean value) {
        this.planOfCareDay4Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay5Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay5Indicator() {
        return planOfCareDay5Indicator;
    }

    /**
     * Sets the value of the planOfCareDay5Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay5Indicator(Boolean value) {
        this.planOfCareDay5Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay6Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay6Indicator() {
        return planOfCareDay6Indicator;
    }

    /**
     * Sets the value of the planOfCareDay6Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay6Indicator(Boolean value) {
        this.planOfCareDay6Indicator = value;
    }

    /**
     * Gets the value of the planOfCareDay7Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfCareDay7Indicator() {
        return planOfCareDay7Indicator;
    }

    /**
     * Sets the value of the planOfCareDay7Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfCareDay7Indicator(Boolean value) {
        this.planOfCareDay7Indicator = value;
    }

    /**
     * Gets the value of the planOfCareHoursPerDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPlanOfCareHoursPerDay() {
        return planOfCareHoursPerDay;
    }

    /**
     * Sets the value of the planOfCareHoursPerDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPlanOfCareHoursPerDay(BigDecimal value) {
        this.planOfCareHoursPerDay = value;
    }

}
