//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 11:05:46 PM EDT 
//


package com.sandata.lab.data.model.dl.model;

import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.Adapter1;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.Date;


/**
 * The lists of tasks that were performed during a specified visit
 * 
 * <p>Java class for Visit_Task_List complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Visit_Task_List">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Visit_Task_List_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Visit_Task_List_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Visit_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Business_Entity_Task_ID" use="required" type="{}Business_Entity_Task_ID" />
 *       &lt;attribute name="Critical_Task_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Visit_Task_Scheduled_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Visit_Task_Performed_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Visit_Task_Not_Performed_Reason">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Visit_Task_Comment" type="{}Comment_Long" />
 *       &lt;attribute name="Task_Results_Reading_Type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Task_Results_Reading_Value" type="{}Reading_Value" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Visit_Task_List")
@OracleMetadata(
        packageName = "PKG_VISIT",
        insertMethod = "insertVisitTaskLst",
        updateMethod = "updateVisitTaskLst",
        deleteMethod = "deleteVisitTaskLst",
        getMethod = "getVisitTaskLst",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.VisitTaskLstT",
        primaryKeys = {})
public class VisitTaskList extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlAttribute(name = "Visit_Task_List_SK", required = true)
    @SerializedName("VisitTaskListSK")
	@Mapping(getter = "getVisitTaskLstSk", setter = "setVisitTaskLstSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger visitTaskListSK;
    @XmlAttribute(name = "Visit_Task_List_ID", required = true)
    @SerializedName("VisitTaskListID")
	@Mapping(getter = "getVisitTaskLstId", setter = "setVisitTaskLstId", type = "String", index = 1)
    protected String visitTaskListID;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(com.sandata.lab.data.model.Adapter1.class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(Adapter1.class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 4)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Business_Entity_ID", required = true)
    @SerializedName("BusinessEntityID")
	@Mapping(getter = "getBeId", setter = "setBeId", type = "String", index = 5)
    protected String businessEntityID;
    @XmlAttribute(name = "Visit_SK", required = true)
    @SerializedName("VisitSK")
	@Mapping(getter = "getVisitSk", setter = "setVisitSk", type = "java.math.BigDecimal", index = 6)
    protected BigInteger visitSK;
    @XmlAttribute(name = "Business_Entity_Task_ID", required = true)
    @SerializedName("BusinessEntityTaskID")
	@Mapping(getter = "getBeTaskId", setter = "setBeTaskId", type = "String", index = 7)
    protected String businessEntityTaskID;
    @XmlAttribute(name = "Critical_Task_Indicator")
    @SerializedName("CriticalTaskIndicator")
	@Mapping(getter = "getCriticalTaskInd", setter = "setCriticalTaskInd", type = "java.math.BigDecimal", index = 8)
    protected Boolean criticalTaskIndicator;
    @XmlAttribute(name = "Visit_Task_Scheduled_Indicator")
    @SerializedName("VisitTaskScheduledIndicator")
	@Mapping(getter = "getVisitTaskScheduledInd", setter = "setVisitTaskScheduledInd", type = "java.math.BigDecimal", index = 9)
    protected Boolean visitTaskScheduledIndicator;
    @XmlAttribute(name = "Visit_Task_Performed_Indicator")
    @SerializedName("VisitTaskPerformedIndicator")
	@Mapping(getter = "getVisitTaskPerfInd", setter = "setVisitTaskPerfInd", type = "java.math.BigDecimal", index = 10)
    protected Boolean visitTaskPerformedIndicator;
    @XmlAttribute(name = "Visit_Task_Not_Performed_Reason")
    @SerializedName("VisitTaskNotPerformedReason")
	@Mapping(getter = "getVisitTaskNotPerfReason", setter = "setVisitTaskNotPerfReason", type = "String", index = 11)
    protected String visitTaskNotPerformedReason;
    @XmlAttribute(name = "Visit_Task_Comment")
    @SerializedName("VisitTaskComment")
	@Mapping(getter = "getVisitTaskComment", setter = "setVisitTaskComment", type = "String", index = 12)
    protected String visitTaskComment;
    @XmlAttribute(name = "Task_Results_Reading_Type")
    @SerializedName("TaskResultsReadingType")
	@Mapping(getter = "getTaskResultsRdngTyp", setter = "setTaskResultsRdngTyp", type = "String", index = 13)
    protected String taskResultsReadingType;
    @XmlAttribute(name = "Task_Results_Reading_Value")
    @SerializedName("TaskResultsReadingValue")
	@Mapping(getter = "getTaskResultsRdngVal", setter = "setTaskResultsRdngVal", type = "String", index = 14)
    protected String taskResultsReadingValue;

    @SerializedName("VisitTaskConfirmationQualifier")
    @Mapping(getter = "getVisitTaskCnfrmQlfr", setter = "setVisitTaskCnfrmQlfr", type = "String", index = 15)
    protected VisitEventPatientConfirmationQualifier visitTaskConfirmationQualifier;


    @SerializedName("VisitTaskTypeCode")
    @Mapping(getter = "getVisitTaskTypCode", setter = "setVisitTaskTypCode", type = "String", index = 16)
    protected VisitTaskTypeCode visitTaskTypeCode;

    /**
     * Gets the value of the visitTaskListSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVisitTaskListSK() {
        return visitTaskListSK;
    }

    /**
     * Sets the value of the visitTaskListSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVisitTaskListSK(BigInteger value) {
        this.visitTaskListSK = value;
    }

    /**
     * Gets the value of the visitTaskListID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitTaskListID() {
        return visitTaskListID;
    }

    /**
     * Sets the value of the visitTaskListID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitTaskListID(String value) {
        this.visitTaskListID = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the businessEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityID() {
        return businessEntityID;
    }

    /**
     * Sets the value of the businessEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityID(String value) {
        this.businessEntityID = value;
    }

    /**
     * Gets the value of the visitSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVisitSK() {
        return visitSK;
    }

    /**
     * Sets the value of the visitSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVisitSK(BigInteger value) {
        this.visitSK = value;
    }

    /**
     * Gets the value of the businessEntityTaskID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityTaskID() {
        return businessEntityTaskID;
    }

    /**
     * Sets the value of the businessEntityTaskID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityTaskID(String value) {
        this.businessEntityTaskID = value;
    }

    /**
     * Gets the value of the criticalTaskIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCriticalTaskIndicator() {
        return criticalTaskIndicator;
    }

    /**
     * Sets the value of the criticalTaskIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCriticalTaskIndicator(Boolean value) {
        this.criticalTaskIndicator = value;
    }

    /**
     * Gets the value of the visitTaskScheduledIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisitTaskScheduledIndicator() {
        return visitTaskScheduledIndicator;
    }

    /**
     * Sets the value of the visitTaskScheduledIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisitTaskScheduledIndicator(Boolean value) {
        this.visitTaskScheduledIndicator = value;
    }

    /**
     * Gets the value of the visitTaskPerformedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisitTaskPerformedIndicator() {
        return visitTaskPerformedIndicator;
    }

    /**
     * Sets the value of the visitTaskPerformedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisitTaskPerformedIndicator(Boolean value) {
        this.visitTaskPerformedIndicator = value;
    }

    /**
     * Gets the value of the visitTaskNotPerformedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitTaskNotPerformedReason() {
        return visitTaskNotPerformedReason;
    }

    /**
     * Sets the value of the visitTaskNotPerformedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitTaskNotPerformedReason(String value) {
        this.visitTaskNotPerformedReason = value;
    }

    /**
     * Gets the value of the visitTaskComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitTaskComment() {
        return visitTaskComment;
    }

    /**
     * Sets the value of the visitTaskComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitTaskComment(String value) {
        this.visitTaskComment = value;
    }

    /**
     * Gets the value of the taskResultsReadingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskResultsReadingType() {
        return taskResultsReadingType;
    }

    /**
     * Sets the value of the taskResultsReadingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskResultsReadingType(String value) {
        this.taskResultsReadingType = value;
    }

    /**
     * Gets the value of the taskResultsReadingValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskResultsReadingValue() {
        return taskResultsReadingValue;
    }

    /**
     * Sets the value of the taskResultsReadingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskResultsReadingValue(String value) {
        this.taskResultsReadingValue = value;
    }

    public VisitEventPatientConfirmationQualifier getVisitTaskConfirmationQualifier() {
        return visitTaskConfirmationQualifier;
    }

    public void setVisitTaskConfirmationQualifier(VisitEventPatientConfirmationQualifier visitTaskConfirmationQualifier) {
        this.visitTaskConfirmationQualifier = visitTaskConfirmationQualifier;
    }

    public VisitTaskTypeCode getVisitTaskTypeCode() {
        return visitTaskTypeCode;
    }

    public void setVisitTaskTypeCode(VisitTaskTypeCode visitTaskTypeCode) {
        this.visitTaskTypeCode = visitTaskTypeCode;
    }
}
