//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


package com.sandata.lab.data.model.dl.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Visit_Verification_Rounding_Rule_ID.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Visit_Verification_Rounding_Rule_ID">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="50"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="A"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Visit_Verification_Rounding_Rule_ID")
@XmlEnum
public enum VisitVerificationRoundingRuleID {


    /**
     * Actual visit hours.
     * 
     */
    N,

    /**
     * Actual visit hours rounded to optional minutes.
     * 
     */
    A;

    public String value() {
        return name();
    }

    public static VisitVerificationRoundingRuleID fromValue(String v) {
        return valueOf(v);
    }

}
