SELECT Visit.VISIT_SK,
        Patient.PT_ID,PT_MEDICAID_ID,PT_FIRST_NAME,PT_LAST_NAME,PT_MIDDLE_NAME,PT_DOB,PT_DISCHARGE_DATE,
        PT_PHONE,PT_ADDR1,PT_ADDR2,PT_APT_NUM,PT_CITY,PT_STATE,PT_PSTL_CODE,PT_ZIP4,PT_COUNTY,PT_PRIO_LVL_CODE,
        ThirdPartyPatientID.PT_ID_NUM AS THIRD_PARTY_PT_ID,
        AdminStaffManager.ADMIN_STAFF_ID AS ManagerID,
        AdminStaffManager.ADMIN_STAFF_FIRST_NAME AS ManagerFirstName,
        AdminStaffManager.ADMIN_STAFF_LAST_NAME AS ManagerLastName,
        AdminStaffCoordinator.ADMIN_STAFF_ID AS CoordinatorID,
        AdminStaffCoordinator.ADMIN_STAFF_FIRST_NAME AS CoordinatorFirstName,
        AdminStaffCoordinator.ADMIN_STAFF_LAST_NAME AS CoordinatorLastName

  FROM PT Patient

  INNER JOIN (SELECT VISIT_SK,PT_ID,BE_ID,STAFF_ID
    FROM VISIT) Visit
  ON Patient.PT_ID = Visit.PT_ID AND Patient.BE_ID = Visit.BE_ID

  LEFT JOIN (SELECT BE_ID,PT_ID,PT_ID_NUM
    FROM PT_ID_XWALK WHERE ROWNUM <=1) ThirdPartyPatientID
  ON ThirdPartyPatientID.PT_ID = Visit.PT_ID AND ThirdPartyPatientID.BE_ID = Visit.BE_ID

  LEFT JOIN (SELECT BE_ID,PT_ID,PT_PHONE,PT_PHONE_ANI_ENABLED_IND
      FROM PT_CONT_PHONE
        WHERE TO_CHAR(REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND CURR_REC_IND = 1
          AND PT_PHONE_PRMY_IND = 1) PatientPhone
    ON Visit.BE_ID = PatientPhone.BE_ID
      AND Visit.PT_ID = PatientPhone.PT_ID

  LEFT JOIN (SELECT BE_ID,PT_ID,PT_ADDR_TYP_NAME,
                      PT_ADDR1,PT_ADDR2,PT_APT_NUM,PT_CITY,PT_STATE,PT_PSTL_CODE,PT_ZIP4,PT_COUNTY
      FROM PT_CONT_ADDR
        WHERE TO_CHAR(REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND CURR_REC_IND = 1
          AND ADDR_PRIO_NAME = 'PRIMARY') PatientAddress
    ON Visit.BE_ID = PatientAddress.BE_ID
      AND Visit.PT_ID = PatientAddress.PT_ID

    -- Staff Coordinator
    LEFT JOIN (SELECT XREF.BE_ID,XREF.STAFF_ID,XREF.ADMIN_STAFF_ID,
                COORDINATOR.ADMIN_STAFF_FIRST_NAME,COORDINATOR.ADMIN_STAFF_LAST_NAME
      FROM ADMIN_STAFF_STAFF_XREF XREF
        INNER JOIN (SELECT BE_ID,ADMIN_STAFF_ID,ADMIN_STAFF_FIRST_NAME,ADMIN_STAFF_LAST_NAME
          FROM ADMIN_STAFF
            WHERE TO_CHAR(REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND CURR_REC_IND = 1) COORDINATOR
        ON XREF.BE_ID = COORDINATOR.BE_ID AND XREF.ADMIN_STAFF_ID = COORDINATOR.ADMIN_STAFF_ID
        WHERE XREF.ADMIN_STAFF_ROLE_NAME = 'COORDINATOR'
            AND TO_CHAR(XREF.REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND XREF.CURR_REC_IND = 1) AdminStaffCoordinator
    ON Visit.BE_ID = AdminStaffCoordinator.BE_ID
      AND Visit.STAFF_ID = AdminStaffCoordinator.STAFF_ID

      -- Staff Manager
      LEFT JOIN (SELECT XREF.BE_ID,XREF.STAFF_ID,XREF.ADMIN_STAFF_ID,
                  MANAGER.ADMIN_STAFF_FIRST_NAME,MANAGER.ADMIN_STAFF_LAST_NAME
        FROM ADMIN_STAFF_STAFF_XREF XREF
          INNER JOIN (SELECT BE_ID,ADMIN_STAFF_ID,ADMIN_STAFF_FIRST_NAME,ADMIN_STAFF_LAST_NAME
            FROM ADMIN_STAFF
              WHERE TO_CHAR(REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND CURR_REC_IND = 1) MANAGER
          ON XREF.BE_ID = MANAGER.BE_ID AND XREF.ADMIN_STAFF_ID = MANAGER.ADMIN_STAFF_ID
          WHERE XREF.ADMIN_STAFF_ROLE_NAME = 'MANAGER'
              AND TO_CHAR(XREF.REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND XREF.CURR_REC_IND = 1) AdminStaffManager
      ON Visit.BE_ID = AdminStaffManager.BE_ID
        AND Visit.STAFF_ID = AdminStaffManager.STAFF_ID

WHERE Visit.VISIT_SK = 755225;
