package com.sandata.lab.rules.call.matching.ceprules;

import com.sandata.lab.rules.call.model.Call;
import com.sandata.lab.rules.call.model.Schedule;
import com.sandata.lab.rules.call.model.UnplannedVisit;
import com.sandata.lab.rules.call.model.State;

global java.util.List schedules;
global com.sandata.lab.rules.call.model.CallPreferences callPreferences;

function boolean staffXOfNine(int x, String staffId1, String staffId2) {
	boolean matched = false;
	int pos = 10 - x;
	for(int i = 0; i < pos; i++) {
		if(staffId2.indexOf(staffId1.substring(i,i+x)) != -1 ) {
			matched = true;
			break;
		}
	}
	return matched;
}
//import function com.sandata.lab.calls.matching.model.Schedule.diff
declare SchedulePruner
 	scheduleId : long @key
 	staffId : String @key
 	@role(envent)
 	@expires(5m)
 end
 
declare Schedule
	@role(event)
	@timestamp(startTime)
	@duration(timeSpan)
end

declare Call
	@role(event)
	@timestamp(callInTime)	
end


rule "calls-rules-0 load schedules "
salience 1000
agenda-group "Load Schedules"
when
	$s : Schedule(state == State.LOADED) //over window:time( 1m )
then
	$s.setState(State.NOT_MATCHED);
	update($s);
	
end

rule "calls-rules-1 VisitEventFact made during schedule Best Case"
salience 1000
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.MATCHED  || state == State.IN_PROGRESS)
	$call : Call( state == State.NOT_MATCHED, this during $schedule, staffId == $schedule.staffId, ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.MATCHED);
	//System.out.println("VisitEventFact with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
	//System.out.println("Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 

rule "calls-rules-1 VisitEventFact made during schedule and matched 7 of 9"
salience 975
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.MATCHED || state == State.IN_PROGRESS)
	$call : Call( state == State.NOT_MATCHED, this during $schedule, staffXOfNine(7, staffId, $schedule.staffId), ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.MATCHED);
//	System.out.println("VisitEventFact 7of9 with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
//	System.out.println("Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 

rule "calls-rules-1 VisitEventFact made during schedule and matched 6 of 9"
salience 970
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.MATCHED || state == State.IN_PROGRESS )
	$call : Call( state == State.NOT_MATCHED, this during $schedule, staffXOfNine(6, staffId, $schedule.staffId), ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.MATCHED);
//	System.out.println("VisitEventFact 6of9 with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
//	System.out.println("Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 

rule "calls-rules-2 set callinTime when when calls is closer to startTime and callin is empty"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.MATCHED, scheduleId == $call.scheduleId, callIn == null, Schedule.diff(startTime,$call.callInTime) < Schedule.diff(endTime,$call.callInTime))
then
    //$schedule.setState(State.INSERTED); A calls gets inserted not a schedule
    $call.setState(State.INSERTED);
    $schedule.setCallIn($call.getCallInTime());
    $schedule.setCallCallIn($call);
    $schedule.setState(State.IN_PROGRESS);
    retract($call);
//    System.out.println("INSERTED Callin (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " < " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end

rule "calls-rules-2-3 set calloutTime when calls is closer to endTime and callout is empty and calls in is empty or > 5 NOT EXTRANEOUS"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule ( (state == State.MATCHED  || state == State.IN_PROGRESS) && scheduleId == $call.scheduleId && callOut == null && Schedule.diff(startTime,$call.callInTime) >= Schedule.diff(endTime,$call.callInTime) && 
	(callIn == null || Schedule.diff(callIn, $call.callInTime) > callPreferences.getMinVisitDurationMS() ) )
	
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.INSERTED);
    $schedule.setCallOut($call.getCallInTime());
    $schedule.setCallCallOut($call);
    $schedule.setState(State.IN_PROGRESS);
    retract($call);
    //System.out.println("INSERTED Callout (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end
//==================================Extraneous VisitEventFact rule 3========================================
rule "calls-rules-3 DONT set calloutTime when callout empty and callin populated and < 5 EXTRANEOUS"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.IN_PROGRESS && scheduleId == $call.scheduleId && callOut == null &&  
	(callIn != null && Schedule.diff(callIn, $call.callInTime) <= callPreferences.getMinVisitDurationMS() ) )
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.EXTRANEOUS);
    $schedule.addExtraneousCalls($call);
    //$schedule.setCallOut($calls.getCallInTime());Dont set it fails minimum visit time
    $schedule.setState(State.IN_PROGRESS);
    retract($call);
    //System.out.println("Extraneous calls (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end

rule "calls-rules-2-3 Move calloutTime to callintime when callintime empty and when callout populated and < 5 EXTRANEOUS added"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.IN_PROGRESS && scheduleId == $call.scheduleId && callIn == null && callOut != null && Schedule.diff(startTime,$call.callInTime) >= Schedule.diff(endTime,$call.callInTime) && 
	(Schedule.diff(callOut, $call.callInTime) <= callPreferences.getMinVisitDurationMS() ) )
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.EXTRANEOUS);
    $schedule.addExtraneousCalls($call);
    $schedule.setCallIn($schedule.getCallOut());//move it to first now since we had a second calls
    $schedule.setCallOut(null);
    $schedule.setCallCallIn($schedule.getCallCallOut());
    $schedule.setCallCallOut(null);
    retract($call);
    //System.out.println("Extraneous calls (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end

rule "calls-rules-2-3 make old calloutTime EXTRANEOUS and replace when callout populated and < 5 callout added"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.IN_PROGRESS && scheduleId == $call.scheduleId && callIn != null && callOut != null && Schedule.diff(startTime,$call.callInTime) >= Schedule.diff(endTime,$call.callInTime) && 
	(Schedule.diff(callOut, $call.callInTime) <= callPreferences.getMinVisitDurationMS() ) )
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.INSERTED);
    $schedule.getCallCallOut().setState(State.EXTRANEOUS);
    $schedule.addExtraneousCalls($schedule.getCallCallOut());
    $schedule.setCallOut($call.getCallInTime());
    $schedule.setCallCallOut($call);
    retract($call);
    //System.out.println("Extraneous calls (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end

rule "calls-rules-2-3 set calloutTime when calls is after schedule.callouttime and > 5 NOT EXTRANEOUS move old callouttime to extraneous"
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.IN_PROGRESS && scheduleId == $call.scheduleId && callOut != null && Schedule.diff(startTime,$call.callInTime) >= Schedule.diff(endTime,$call.callInTime) && 
	(callIn != null && callOut before $call.callInTime && Schedule.diff(callOut, $call.callInTime) > callPreferences.getMinVisitDurationMS() ) )
	
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.INSERTED);
    $schedule.setCallOut($call.getCallInTime());
    $schedule.addExtraneousCalls($schedule.getCallCallOut());
    $schedule.setCallCallOut($call);
    retract($call);
    //System.out.println("INSERTED Callout (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    update($schedule);
end

rule "calls-rules-5 ADD EXTRANEOUS" // should never happen from calls server
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule (state == State.IN_PROGRESS && scheduleId == $call.scheduleId && callOut != null && callIn != null && 
	callOut after $call.callInTime && callIn before $call.callInTime )
	
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.EXTRANEOUS);
    $schedule.addExtraneousCalls($call);
    retract($call);
    //System.out.println("ADD EXTRANEOUS CALL IN BETWEEN");
    //System.out.println("( schedule.callOut " + $schedule.getCallOut().toString() + " after callInTime " + $calls.getCallInTime().toString() + " )" );
    //System.out.println("( schedule.callIn " + $schedule.getCallIn().toString() + " before callInTime " + $calls.getCallInTime().toString() + " )" );
    update($schedule);
end

//==================================================================================================
rule "calls-rules-5 set calloutTime when callout populated > 5 NOT EXTRANEOUS callin is empty "
salience 900
when
	$call : Call( state == State.MATCHED)
	$schedule : Schedule ( (state == State.MATCHED  || state == State.IN_PROGRESS) && scheduleId == $call.scheduleId && callIn == null && callOut != null && Schedule.diff(startTime,$call.callInTime) >= Schedule.diff(endTime,$call.callInTime) && 
	(Schedule.diff(callOut, $call.callInTime) > callPreferences.getMinVisitDurationMS() ) )
then
    //$schedule.setState(State.INSERTED); Cant insert a schedule
    $call.setState(State.INSERTED);
    $schedule.setState(State.IN_PROGRESS);
    $schedule.setCallCallIn($schedule.getCallCallOut());
    $schedule.setCallCallOut($call);
    $schedule.setCallOut($call.getCallInTime());
    update($schedule)
    retract($call);
    //System.out.println("Extraneous calls (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + " >= " + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
    //
end

//============================================== 24Hours match==============================

rule "calls-rules-12-identify-the-schedule VisitEventFact made within 24 hours schedule"
salience 900
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.IN_PROGRESS)
	$call : Call( state == State.NOT_MATCHED, this during[-24h, 48h] $schedule, staffId == $schedule.staffId, ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.IN_PROGRESS);
	//System.out.println("VisitEventFact with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
	//System.out.println("24h rule fired Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 

rule "calls-rules-12-identify-the-schedule VisitEventFact made within 24 hours schedule 7 Of 9"
salience 900
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.IN_PROGRESS)
	$call : Call( state == State.NOT_MATCHED, this during[-24h, 48h] $schedule, staffXOfNine(7, staffId, $schedule.staffId), ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.IN_PROGRESS);
	//System.out.println("VisitEventFact with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
	//System.out.println("24h rule fired Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 
rule "calls-rules-12-identify-the-schedule VisitEventFact made within 24 hours schedule 6 of 9"
salience 900
when
	$schedule : Schedule( state == State.NOT_MATCHED || state == State.IN_PROGRESS)
	$call : Call( state == State.NOT_MATCHED, this during[-24h, 48h] $schedule, staffXOfNine(6, staffId, $schedule.staffId), ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$call.setScheduleId($schedule.getScheduleId());
	$schedule.setState(State.IN_PROGRESS);
	//System.out.println("VisitEventFact with a visitId of " + $calls.getVisitId() + " matched with schedule with scheduleId of " + $schedule.getScheduleId() + ".");
	//System.out.println("24h rule fired Time diffs are (" + Long.toString(Schedule.diff($schedule.getStartTime(),$calls.getCallInTime())) + ") and (" + Long.toString(Schedule.diff($schedule.getEndTime(),$calls.getCallInTime())) + ")");
	insert(new SchedulePruner($schedule.getScheduleId(),$schedule.getStaffId()));
	update($call);
	update($schedule);
end	 

rule "calls-rules-12 END EXISTING ON NEW VISIT"
salience 900
when
	$pruner : SchedulePruner()
	$schedule : Schedule( staffId == $pruner.staffId && (state == State.IN_PROGRESS || state == State.MATCHED) && scheduleId != $pruner.scheduleId)
then
	$schedule.setState(State.ENDED);
	update($schedule);
	retract($pruner);
end

rule "calls-rules-4 There was a break on this visit"//this scheduled visit would have been updated already by last calls.
salience 900
when
	$schedule : Schedule(state == State.ENDED)
	$call : Call( state == State.NOT_MATCHED, staffId == $schedule.staffId, ani == $schedule.callerIdForPatient )
then
	$call.setState(State.MATCHED);
	$schedule.setState(State.ENDED);
	$schedule.deleteExtraneousCalls();
	$schedule.setCallCallIn($call);
	$schedule.setCallCallOut(null);
	insert ( new UnplannedVisit($schedule, $call.getCallInTime(), null));
	retract($call)
	retract($schedule);	
end

