/*
 * Copyright (c) 2015. Sandata Technologies, LLC
 * 26 Harbor Park Drive, Port Washington, NY 11050, 800-544-7263
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of Sandata Technologies, LLC
 * ("Confidential Information"). You shall not disclose such Confidential Information and shall
 * use it only in accordance with the terms of the license agreement you entered into with
 * Sandata.
 */

package com.sandata.lab.rest.oracle.utils.constants;


public class App {

    public enum ID {

        REST_ROUTE_ENDPOINT ("RESTFUL_ORACLE_DATA_ROUTE"),

        // INSERT
        REST_PATIENT_INSERT ("REST_PATIENT_INSERT"),
        REST_PATIENT_SERVICES_INSERT ("REST_PATIENT_SERVICES_INSERT"),
        REST_PATIENT_BUSINESS_ENTITY_INSERT ("REST_PATIENT_BUSINESS_ENTITY_INSERT"),
        REST_PATIENT_CROSSWALK_INSERT ("REST_PATIENT_CROSSWALK_INSERT"),
        REST_PATIENT_SAFETY_MEASURES_INSERT ("REST_PATIENT_SAFETY_MEASURES_INSERT"),
        REST_PATIENT_ENVIRONMENT_INSERT ("REST_PATIENT_ENVIRONMENT_INSERT"),
        REST_PATIENT_SCHEDULED_EVENT_INSERT ("REST_PATIENT_SCHEDULED_EVENT_INSERT"),
        REST_PATIENT_PAYER_INSERT ("REST_PATIENT_PAYER_INSERT"),
        REST_PATIENT_AUTHORIZATION_INSERT ("REST_PATIENT_AUTHORIZATION_INSERT"),
        REST_PATIENT_EXCLUDED_INSERT ("REST_PATIENT_EXCLUDED_INSERT"),
        REST_PATIENT_STAFF_HISTORY_INSERT ("REST_PATIENT_STAFF_HISTORY_INSERT"),
        REST_PATIENT_ELIGIBILITY_INSERT ("REST_PATIENT_ELIGIBILITY_INSERT"),
        REST_PATIENT_NUTRITIONAL_REQS_INSERT ("REST_PATIENT_NUTRITIONAL_REQS_INSERT"),
        REST_PATIENT_CLINICAL_ASSESSMENT_INSERT ("REST_PATIENT_CLINICAL_ASSESSMENT_INSERT"),
        REST_PATIENT_ALLERGIES_INSERT ("REST_PATIENT_ALLERGIES_INSERT"),
        REST_PATIENT_INTAKE_INSERT ("REST_PATIENT_INTAKE_INSERT"),
        REST_PATIENT_CONTACT_DETAILS_INSERT ("REST_PATIENT_CONTACT_DETAILS_INSERT"),
        REST_PATIENT_TASK_INSERT ("REST_PATIENT_TASK_INSERT"),
        REST_PATIENT_REFERENCE_INSERT ("REST_PATIENT_REFERENCE_INSERT"),
        REST_PATIENT_DME_SUPPLIES_INSERT ("REST_PATIENT_DME_SUPPLIES_INSERT"),
        REST_PATIENT_VISIT_INSERT ("REST_PATIENT_VISIT_INSERT"),
        REST_PATIENT_PLAN_OF_CARE_INSERT ("REST_PATIENT_PLAN_OF_CARE_INSERT"),
        REST_PATIENT_REQUIREMENTS_INSERT ("REST_PATIENT_REQUIREMENTS_INSERT"),
        REST_PATIENT_MEDICATIONS_INSERT ("REST_PATIENT_MEDICATIONS_INSERT"),
        REST_PATIENT_BILL_RATE_INSERT ("REST_PATIENT_BILL_RATE_INSERT"),
        REST_PATIENT_MEDICAL_HIST_INSERT ("REST_PATIENT_MEDICAL_HIST_INSERT"),

        //UPDATE
        REST_PATIENT_UPDATE ("REST_PATIENT_UPDATE"),
        REST_PATIENT_SERVICES_UPDATE ("REST_PATIENT_SERVICES_UPDATE"),
        REST_PATIENT_BUSINESS_ENTITY_UPDATE ("REST_PATIENT_BUSINESS_ENTITY_UPDATE"),
        REST_PATIENT_CROSSWALK_UPDATE ("REST_PATIENT_CROSSWALK_UPDATE"),
        REST_PATIENT_SAFETY_MEASURES_UPDATE ("REST_PATIENT_SAFETY_MEASURES_UPDATE"),
        REST_PATIENT_ENVIRONMENT_UPDATE ("REST_PATIENT_ENVIRONMENT_UPDATE"),
        REST_PATIENT_SCHEDULED_EVENT_UPDATE ("REST_PATIENT_SCHEDULED_EVENT_UPDATE"),
        REST_PATIENT_PAYER_UPDATE ("REST_PATIENT_PAYER_UPDATE"),
        REST_PATIENT_AUTHORIZATION_UPDATE ("REST_PATIENT_AUTHORIZATION_UPDATE"),
        REST_PATIENT_EXCLUDED_UPDATE ("REST_PATIENT_EXCLUDED_UPDATE"),
        REST_PATIENT_STAFF_HISTORY_UPDATE ("REST_PATIENT_STAFF_HISTORY_UPDATE"),
        REST_PATIENT_ELIGIBILITY_UPDATE ("REST_PATIENT_ELIGIBILITY_UPDATE"),
        REST_PATIENT_NUTRITIONAL_REQS_UPDATE ("REST_PATIENT_NUTRITIONAL_REQS_UPDATE"),
        REST_PATIENT_CLINICAL_ASSESSMENT_UPDATE ("REST_PATIENT_CLINICAL_ASSESSMENT_UPDATE"),
        REST_PATIENT_ALLERGIES_UPDATE ("REST_PATIENT_ALLERGIES_UPDATE"),
        REST_PATIENT_INTAKE_UPDATE ("REST_PATIENT_INTAKE_UPDATE"),
        REST_PATIENT_CONTACT_DETAILS_UPDATE ("REST_PATIENT_CONTACT_DETAILS_UPDATE"),
        REST_PATIENT_TASK_UPDATE ("REST_PATIENT_TASK_UPDATE"),
        REST_PATIENT_REFERENCE_UPDATE ("REST_PATIENT_REFERENCE_UPDATE"),
        REST_PATIENT_DME_SUPPLIES_UPDATE ("REST_PATIENT_DME_SUPPLIES_UPDATE"),
        REST_PATIENT_VISIT_UPDATE ("REST_PATIENT_VISIT_UPDATE"),
        REST_PATIENT_PLAN_OF_CARE_UPDATE ("REST_PATIENT_PLAN_OF_CARE_UPDATE"),
        REST_PATIENT_REQUIREMENTS_UPDATE ("REST_PATIENT_REQUIREMENTS_UPDATE"),
        REST_PATIENT_MEDICATIONS_UPDATE ("REST_PATIENT_MEDICATIONS_UPDATE"),
        REST_PATIENT_BILL_RATE_UPDATE ("REST_PATIENT_BILL_RATE_UPDATE"),
        REST_PATIENT_MEDICAL_HIST_UPDATE ("REST_PATIENT_MEDICAL_HIST_UPDATE"),

        // DELETE
        REST_PATIENT_DELETE ("REST_PATIENT_DELETE"),
        REST_PATIENT_SERVICES_DELETE ("REST_PATIENT_SERVICES_DELETE"),
        REST_PATIENT_BUSINESS_ENTITY_DELETE ("REST_PATIENT_BUSINESS_ENTITY_DELETE"),
        REST_PATIENT_CROSSWALK_DELETE ("REST_PATIENT_CROSSWALK_DELETE"),
        REST_PATIENT_SAFETY_MEASURES_DELETE ("REST_PATIENT_SAFETY_MEASURES_DELETE"),
        REST_PATIENT_ENVIRONMENT_DELETE ("REST_PATIENT_ENVIRONMENT_DELETE"),
        REST_PATIENT_SCHEDULED_EVENT_DELETE ("REST_PATIENT_SCHEDULED_EVENT_DELETE"),
        REST_PATIENT_PAYER_DELETE ("REST_PATIENT_PAYER_DELETE"),
        REST_PATIENT_AUTHORIZATION_DELETE ("REST_PATIENT_AUTHORIZATION_DELETE"),
        REST_PATIENT_EXCLUDED_DELETE ("REST_PATIENT_EXCLUDED_DELETE"),
        REST_PATIENT_STAFF_HISTORY_DELETE ("REST_PATIENT_STAFF_HISTORY_DELETE"),
        REST_PATIENT_ELIGIBILITY_DELETE ("REST_PATIENT_ELIGIBILITY_DELETE"),
        REST_PATIENT_NUTRITIONAL_REQS_DELETE ("REST_PATIENT_NUTRITIONAL_REQS_DELETE"),
        REST_PATIENT_CLINICAL_ASSESSMENT_DELETE ("REST_PATIENT_CLINICAL_ASSESSMENT_DELETE"),
        REST_PATIENT_ALLERGIES_DELETE ("REST_PATIENT_ALLERGIES_DELETE"),
        REST_PATIENT_INTAKE_DELETE ("REST_PATIENT_INTAKE_DELETE"),
        REST_PATIENT_CONTACT_DETAILS_DELETE ("REST_PATIENT_CONTACT_DETAILS_DELETE"),
        REST_PATIENT_TASK_DELETE ("REST_PATIENT_TASK_DELETE"),
        REST_PATIENT_REFERENCE_DELETE ("REST_PATIENT_REFERENCE_DELETE"),
        REST_PATIENT_DME_SUPPLIES_DELETE ("REST_PATIENT_DME_SUPPLIES_DELETE"),
        REST_PATIENT_VISIT_DELETE ("REST_PATIENT_VISIT_DELETE"),
        REST_PATIENT_PLAN_OF_CARE_DELETE ("REST_PATIENT_PLAN_OF_CARE_DELETE"),
        REST_PATIENT_REQUIREMENTS_DELETE ("REST_PATIENT_REQUIREMENTS_DELETE"),
        REST_PATIENT_MEDICATIONS_DELETE ("REST_PATIENT_MEDICATIONS_DELETE"),
        REST_PATIENT_BILL_RATE_DELETE ("REST_PATIENT_BILL_RATE_DELETE"),
        REST_PATIENT_MEDICAL_HIST_DELETE ("REST_PATIENT_MEDICAL_HIST_DELETE"),

        // GET
        REST_PATIENT_GET ("REST_PATIENT_GET"),
        REST_PATIENT_SERVICES_GET ("REST_PATIENT_SERVICES_GET"),
        REST_PATIENT_BUSINESS_ENTITY_GET ("REST_PATIENT_BUSINESS_ENTITY_GET"),
        REST_PATIENT_CROSSWALK_GET ("REST_PATIENT_CROSSWALK_GET"),
        REST_PATIENT_SAFETY_MEASURES_GET ("REST_PATIENT_SAFETY_MEASURES_GET"),
        REST_PATIENT_ENVIRONMENT_GET ("REST_PATIENT_ENVIRONMENT_GET"),
        REST_PATIENT_SCHEDULED_EVENT_GET ("REST_PATIENT_SCHEDULED_EVENT_GET"),
        REST_PATIENT_PAYER_GET ("REST_PATIENT_PAYER_GET"),
        REST_PATIENT_AUTHORIZATION_GET ("REST_PATIENT_AUTHORIZATION_GET"),
        REST_PATIENT_EXCLUDED_GET ("REST_PATIENT_EXCLUDED_GET"),
        REST_PATIENT_STAFF_HISTORY_GET ("REST_PATIENT_STAFF_HISTORY_GET"),
        REST_PATIENT_ELIGIBILITY_GET ("REST_PATIENT_ELIGIBILITY_GET"),
        REST_PATIENT_NUTRITIONAL_REQS_GET ("REST_PATIENT_NUTRITIONAL_REQS_GET"),
        REST_PATIENT_CLINICAL_ASSESSMENT_GET ("REST_PATIENT_CLINICAL_ASSESSMENT_GET"),
        REST_PATIENT_ALLERGIES_GET ("REST_PATIENT_ALLERGIES_GET"),
        REST_PATIENT_INTAKE_GET ("REST_PATIENT_INTAKE_GET"),
        REST_PATIENT_CONTACT_DETAILS_GET ("REST_PATIENT_CONTACT_DETAILS_GET"),
        REST_PATIENT_TASK_GET ("REST_PATIENT_TASK_GET"),
        REST_PATIENT_REFERENCE_GET ("REST_PATIENT_REFERENCE_GET"),
        REST_PATIENT_DME_SUPPLIES_GET ("REST_PATIENT_DME_SUPPLIES_GET"),
        REST_PATIENT_VISIT_GET ("REST_PATIENT_VISIT_GET"),
        REST_PATIENT_PLAN_OF_CARE_GET ("REST_PATIENT_PLAN_OF_CARE_GET"),
        REST_PATIENT_REQUIREMENTS_GET ("REST_PATIENT_REQUIREMENTS_GET"),
        REST_PATIENT_MEDICATIONS_GET ("REST_PATIENT_MEDICATIONS_GET"),
        REST_PATIENT_BILL_RATE_GET ("REST_PATIENT_BILL_RATE_GET"),
        REST_PATIENT_MEDICAL_HIST_GET ("REST_PATIENT_MEDICAL_HIST_GET");

        private final String id;

        private ID(final String id) {
            this.id = id;
        }

        @Override
        public String toString() {
            return this.id;
        }
    }
}
