//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


package com.sandata.lab.rest.oracle.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A discrete block of time during an admissoin.  An admission can one or more Admission Periods.
 * 
 * <p>Java class for Admission_Period complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Admission_Period">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Admission_Period_Diagnosis" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Admission_Period_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Admission_Period_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Patient_Intake_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Admission_Period_Effective_Date" use="required" type="{}Attribute_Effective_Date" />
 *       &lt;attribute name="Admission_Period_Termination_Date" type="{}Attribute_Termination_Date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Admission_Period", propOrder = {
    "admissionPeriodDiagnosis"
})
@OracleMetadata(
        packageName = "PKG_ADMIN",
        insertMethod = "insertAdmPrd",
        updateMethod = "updateAdmPrd",
        deleteMethod = "deleteAdmPrd",
        getMethod = "getAdmPrd",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.AdmPrdT",
        primaryKeys = {})
public class AdmissionPeriod extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlElement(name = "Admission_Period_Diagnosis")
    @SerializedName("AdmissionPeriodDiagnosis")
    protected List<AdmissionPeriodDiagnosis> admissionPeriodDiagnosis;
    @XmlAttribute(name = "Admission_Period_SK", required = true)
    @SerializedName("AdmissionPeriodSK")
	@Mapping(getter = "getAdmPrdSk", setter = "setAdmPrdSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger admissionPeriodSK;
    @XmlAttribute(name = "Admission_Period_ID", required = true)
    @SerializedName("AdmissionPeriodID")
	@Mapping(getter = "getAdmPrdId", setter = "setAdmPrdId", type = "String", index = 1)
    protected String admissionPeriodID;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 4)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Patient_Intake_SK", required = true)
    @SerializedName("PatientIntakeSK")
	@Mapping(getter = "getPtIntakeSk", setter = "setPtIntakeSk", type = "java.math.BigDecimal", index = 5)
    protected BigInteger patientIntakeSK;
    @XmlAttribute(name = "Admission_Period_Effective_Date", required = true)
    @SerializedName("AdmissionPeriodEffectiveDate")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getAdmPrdEffDate", setter = "setAdmPrdEffDate", type = "java.sql.Timestamp", index = 6)
    protected Date admissionPeriodEffectiveDate;
    @XmlAttribute(name = "Admission_Period_Termination_Date")
    @SerializedName("AdmissionPeriodTerminationDate")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getAdmPrdTermDate", setter = "setAdmPrdTermDate", type = "java.sql.Timestamp", index = 7)
    protected Date admissionPeriodTerminationDate;

    /**
     * Gets the value of the admissionPeriodDiagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the admissionPeriodDiagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdmissionPeriodDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdmissionPeriodDiagnosis }
     * 
     * 
     */
    public List<AdmissionPeriodDiagnosis> getAdmissionPeriodDiagnosis() {
        if (admissionPeriodDiagnosis == null) {
            admissionPeriodDiagnosis = new ArrayList<AdmissionPeriodDiagnosis>();
        }
        return this.admissionPeriodDiagnosis;
    }

    /**
     * Gets the value of the admissionPeriodSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAdmissionPeriodSK() {
        return admissionPeriodSK;
    }

    /**
     * Sets the value of the admissionPeriodSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAdmissionPeriodSK(BigInteger value) {
        this.admissionPeriodSK = value;
    }

    /**
     * Gets the value of the admissionPeriodID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionPeriodID() {
        return admissionPeriodID;
    }

    /**
     * Sets the value of the admissionPeriodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionPeriodID(String value) {
        this.admissionPeriodID = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the patientIntakeSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPatientIntakeSK() {
        return patientIntakeSK;
    }

    /**
     * Sets the value of the patientIntakeSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPatientIntakeSK(BigInteger value) {
        this.patientIntakeSK = value;
    }

    /**
     * Gets the value of the admissionPeriodEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getAdmissionPeriodEffectiveDate() {
        return admissionPeriodEffectiveDate;
    }

    /**
     * Sets the value of the admissionPeriodEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionPeriodEffectiveDate(Date value) {
        this.admissionPeriodEffectiveDate = value;
    }

    /**
     * Gets the value of the admissionPeriodTerminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getAdmissionPeriodTerminationDate() {
        return admissionPeriodTerminationDate;
    }

    /**
     * Sets the value of the admissionPeriodTerminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionPeriodTerminationDate(Date value) {
        this.admissionPeriodTerminationDate = value;
    }

}
