//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


package com.sandata.lab.rest.oracle.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Interface_Data_Exchange_Format.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Interface_Data_Exchange_Format">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="50"/>
 *     &lt;enumeration value="CSV"/>
 *     &lt;enumeration value="XML"/>
 *     &lt;enumeration value="FIXED LENGTH"/>
 *     &lt;enumeration value="JSON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Interface_Data_Exchange_Format")
@XmlEnum
public enum InterfaceDataExchangeFormat {

    CSV("CSV"),
    XML("XML"),
    @XmlEnumValue("FIXED LENGTH")
    FIXED_LENGTH("FIXED LENGTH"),
    JSON("JSON");
    private final String value;

    InterfaceDataExchangeFormat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterfaceDataExchangeFormat fromValue(String v) {
        for (InterfaceDataExchangeFormat c: InterfaceDataExchangeFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
