//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


package com.sandata.lab.rest.oracle.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import java.math.BigInteger;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * ERROR: String not found in file
 * 
 * <p>Java class for Patient_Designee_Contact_Detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient_Designee_Contact_Detail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Patient_Designee_Contact_Detail_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Effective_Timestamp" use="required" type="{}Record_Effective_Timestamp" />
 *       &lt;attribute name="Record_Termination_Timestamp" use="required" type="{}Record_Termination_Timestamp" />
 *       &lt;attribute name="Record_Created_By" type="{}Record_Created_By" />
 *       &lt;attribute name="Record_Updated_By" type="{}Record_Updated_By" />
 *       &lt;attribute name="Current_Record_Indicator" use="required" type="{}Current_Record_Indicator" />
 *       &lt;attribute name="Change_Reason_Memo" type="{}Change_Reason_Memo" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Patient_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Patient_Designee_Contact_Detail_Type_Name" use="required" type="{}Patient_Designe_Contact_Detail_Type_Name" />
 *       &lt;attribute name="Contact_Relationship">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Patient_Designee_First_Name" type="{}Name" />
 *       &lt;attribute name="Patient_Designee_Middle_Name" type="{}Name" />
 *       &lt;attribute name="Patient_Designee_Last_Name" type="{}Name" />
 *       &lt;attribute name="Patient_Designee_Suffix_Name" type="{}Name_Suffix" />
 *       &lt;attribute name="Patient_Designee_Address_Line_1" type="{}Address_Line" />
 *       &lt;attribute name="Patient_Designee_Address_Line_2" type="{}Address_Line" />
 *       &lt;attribute name="Patient_Designee_City" type="{}City" />
 *       &lt;attribute name="Patient_Designee_State" type="{}State_Code" />
 *       &lt;attribute name="Patient_Designee_Postal_Code" type="{}Postal_Code" />
 *       &lt;attribute name="Patient_Designee_Zip4" type="{}Zip4" />
 *       &lt;attribute name="Patient_Designee_Home_Phone" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Work_Phone" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Mobile_Phone" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Phone_Other" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Phone_Other_1" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Fax" type="{}Phone" />
 *       &lt;attribute name="Patient_Designee_Email" type="{}Email" />
 *       &lt;attribute name="Patient_Designee_Email_Other_1" type="{}Email" />
 *       &lt;attribute name="Patient_Designee_Email_Other_2" type="{}Email" />
 *       &lt;attribute name="Patient_Designee_Email_Other_3" type="{}Email" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient_Designee_Contact_Detail")
@OracleMetadata(
        packageName = "PKG_PD",
        insertMethod = "insertPdContDet",
        updateMethod = "updatePdContDet",
        deleteMethod = "deletePdContDet",
        getMethod = "getPdContDet",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.PdContDetT",
        primaryKeys = {})
public class PatientDesigneeContactDetail extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlAttribute(name = "Patient_Designee_Contact_Detail_SK", required = true)
    @SerializedName("PatientDesigneeContactDetailSK")
	@Mapping(getter = "getPdContDetSk", setter = "setPdContDetSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger patientDesigneeContactDetailSK;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 1)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Record_Effective_Timestamp", required = true)
    @SerializedName("RecordEffectiveTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecEffTmstp", setter = "setRecEffTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordEffectiveTimestamp;
    @XmlAttribute(name = "Record_Termination_Timestamp", required = true)
    @SerializedName("RecordTerminationTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecTermTmstp", setter = "setRecTermTmstp", type = "java.sql.Timestamp", index = 4)
    protected Date recordTerminationTimestamp;
    @XmlAttribute(name = "Record_Created_By")
    @SerializedName("RecordCreatedBy")
	@Mapping(getter = "getRecCreatedBy", setter = "setRecCreatedBy", type = "String", index = 5)
    protected String recordCreatedBy;
    @XmlAttribute(name = "Record_Updated_By")
    @SerializedName("RecordUpdatedBy")
	@Mapping(getter = "getRecUpdatedBy", setter = "setRecUpdatedBy", type = "String", index = 6)
    protected String recordUpdatedBy;
    @XmlAttribute(name = "Current_Record_Indicator", required = true)
    @SerializedName("CurrentRecordIndicator")
	@Mapping(getter = "getCurrRecInd", setter = "setCurrRecInd", type = "java.math.BigDecimal", index = 7)
    protected boolean currentRecordIndicator;
    @XmlAttribute(name = "Change_Reason_Memo")
    @SerializedName("ChangeReasonMemo")
	@Mapping(getter = "getChangeReasonMemo", setter = "setChangeReasonMemo", type = "String", index = 8)
    protected String changeReasonMemo;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 9)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Patient_ID", required = true)
    @SerializedName("PatientID")
	@Mapping(getter = "getPtId", setter = "setPtId", type = "String", index = 10)
    protected String patientID;
    @XmlAttribute(name = "Business_Entity_ID", required = true)
    @SerializedName("BusinessEntityID")
	@Mapping(getter = "getBeId", setter = "setBeId", type = "String", index = 11)
    protected String businessEntityID;
    @XmlAttribute(name = "Patient_Designee_Contact_Detail_Type_Name", required = true)
    @SerializedName("PatientDesigneeContactDetailTypeName")
	@Mapping(getter = "getPdContDetTypName", setter = "setPdContDetTypName", type = "String", index = 12)
    protected PatientDesigneContactDetailTypeName patientDesigneeContactDetailTypeName;
    @XmlAttribute(name = "Contact_Relationship")
    @SerializedName("ContactRelationship")
	@Mapping(getter = "getContRel", setter = "setContRel", type = "String", index = 13)
    protected String contactRelationship;
    @XmlAttribute(name = "Patient_Designee_First_Name")
    @SerializedName("PatientDesigneeFirstName")
	@Mapping(getter = "getPdFirstName", setter = "setPdFirstName", type = "String", index = 14)
    protected String patientDesigneeFirstName;
    @XmlAttribute(name = "Patient_Designee_Middle_Name")
    @SerializedName("PatientDesigneeMiddleName")
	@Mapping(getter = "getPdMiddleName", setter = "setPdMiddleName", type = "String", index = 15)
    protected String patientDesigneeMiddleName;
    @XmlAttribute(name = "Patient_Designee_Last_Name")
    @SerializedName("PatientDesigneeLastName")
	@Mapping(getter = "getPdLastName", setter = "setPdLastName", type = "String", index = 16)
    protected String patientDesigneeLastName;
    @XmlAttribute(name = "Patient_Designee_Suffix_Name")
    @SerializedName("PatientDesigneeSuffixName")
	@Mapping(getter = "getPdSuffixName", setter = "setPdSuffixName", type = "String", index = 17)
    protected String patientDesigneeSuffixName;
    @XmlAttribute(name = "Patient_Designee_Address_Line_1")
    @SerializedName("PatientDesigneeAddressLine1")
	@Mapping(getter = "getPdAddr1", setter = "setPdAddr1", type = "String", index = 18)
    protected String patientDesigneeAddressLine1;
    @XmlAttribute(name = "Patient_Designee_Address_Line_2")
    @SerializedName("PatientDesigneeAddressLine2")
	@Mapping(getter = "getPdAddr2", setter = "setPdAddr2", type = "String", index = 19)
    protected String patientDesigneeAddressLine2;
    @XmlAttribute(name = "Patient_Designee_City")
    @SerializedName("PatientDesigneeCity")
	@Mapping(getter = "getPdCity", setter = "setPdCity", type = "String", index = 20)
    protected String patientDesigneeCity;
    @XmlAttribute(name = "Patient_Designee_State")
    @SerializedName("PatientDesigneeState")
	@Mapping(getter = "getPdState", setter = "setPdState", type = "String", index = 21)
    protected StateCode patientDesigneeState;
    @XmlAttribute(name = "Patient_Designee_Postal_Code")
    @SerializedName("PatientDesigneePostalCode")
	@Mapping(getter = "getPdPstlCode", setter = "setPdPstlCode", type = "String", index = 22)
    protected String patientDesigneePostalCode;
    @XmlAttribute(name = "Patient_Designee_Zip4")
    @SerializedName("PatientDesigneeZip4")
	@Mapping(getter = "getPdHomePhone", setter = "setPdHomePhone", type = "String", index = 23)
    protected String patientDesigneeZip4;
    @XmlAttribute(name = "Patient_Designee_Home_Phone")
    @SerializedName("PatientDesigneeHomePhone")
	@Mapping(getter = "getPdWorkPhone", setter = "setPdWorkPhone", type = "String", index = 24)
    protected String patientDesigneeHomePhone;
    @XmlAttribute(name = "Patient_Designee_Work_Phone")
    @SerializedName("PatientDesigneeWorkPhone")
	@Mapping(getter = "getPdMobilePhone", setter = "setPdMobilePhone", type = "String", index = 25)
    protected String patientDesigneeWorkPhone;
    @XmlAttribute(name = "Patient_Designee_Mobile_Phone")
    @SerializedName("PatientDesigneeMobilePhone")
	@Mapping(getter = "getPdPhoneOther", setter = "setPdPhoneOther", type = "String", index = 26)
    protected String patientDesigneeMobilePhone;
    @XmlAttribute(name = "Patient_Designee_Phone_Other")
    @SerializedName("PatientDesigneePhoneOther")
	@Mapping(getter = "getPdPhoneOther1", setter = "setPdPhoneOther1", type = "String", index = 27)
    protected String patientDesigneePhoneOther;
    @XmlAttribute(name = "Patient_Designee_Phone_Other_1")
    @SerializedName("PatientDesigneePhoneOther1")
	@Mapping(getter = "getPdFax", setter = "setPdFax", type = "String", index = 28)
    protected String patientDesigneePhoneOther1;
    @XmlAttribute(name = "Patient_Designee_Fax")
    @SerializedName("PatientDesigneeFax")
	@Mapping(getter = "getPdEmail", setter = "setPdEmail", type = "String", index = 29)
    protected String patientDesigneeFax;
    @XmlAttribute(name = "Patient_Designee_Email")
    @SerializedName("PatientDesigneeEmail")
	@Mapping(getter = "getPdEmailOther1", setter = "setPdEmailOther1", type = "String", index = 30)
    protected String patientDesigneeEmail;
    @XmlAttribute(name = "Patient_Designee_Email_Other_1")
    @SerializedName("PatientDesigneeEmailOther1")
	@Mapping(getter = "getPdEmailOther2", setter = "setPdEmailOther2", type = "String", index = 31)
    protected String patientDesigneeEmailOther1;
    @XmlAttribute(name = "Patient_Designee_Email_Other_2")
    @SerializedName("PatientDesigneeEmailOther2")
	@Mapping(getter = "getPdEmailOther3", setter = "setPdEmailOther3", type = "String", index = 32)
    protected String patientDesigneeEmailOther2;
    @XmlAttribute(name = "Patient_Designee_Email_Other_3")
    @SerializedName("PatientDesigneeEmailOther3")
	@Mapping(getter = "getPdZip4", setter = "setPdZip4", type = "String", index = 33)
    protected String patientDesigneeEmailOther3;

    /**
     * Gets the value of the patientDesigneeContactDetailSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPatientDesigneeContactDetailSK() {
        return patientDesigneeContactDetailSK;
    }

    /**
     * Sets the value of the patientDesigneeContactDetailSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPatientDesigneeContactDetailSK(BigInteger value) {
        this.patientDesigneeContactDetailSK = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the recordEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordEffectiveTimestamp() {
        return recordEffectiveTimestamp;
    }

    /**
     * Sets the value of the recordEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordEffectiveTimestamp(Date value) {
        this.recordEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the recordTerminationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordTerminationTimestamp() {
        return recordTerminationTimestamp;
    }

    /**
     * Sets the value of the recordTerminationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordTerminationTimestamp(Date value) {
        this.recordTerminationTimestamp = value;
    }

    /**
     * Gets the value of the recordCreatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreatedBy() {
        return recordCreatedBy;
    }

    /**
     * Sets the value of the recordCreatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreatedBy(String value) {
        this.recordCreatedBy = value;
    }

    /**
     * Gets the value of the recordUpdatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdatedBy() {
        return recordUpdatedBy;
    }

    /**
     * Sets the value of the recordUpdatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdatedBy(String value) {
        this.recordUpdatedBy = value;
    }

    /**
     * Gets the value of the currentRecordIndicator property.
     * 
     */
    public boolean isCurrentRecordIndicator() {
        return currentRecordIndicator;
    }

    /**
     * Sets the value of the currentRecordIndicator property.
     * 
     */
    public void setCurrentRecordIndicator(boolean value) {
        this.currentRecordIndicator = value;
    }

    /**
     * Gets the value of the changeReasonMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeReasonMemo() {
        return changeReasonMemo;
    }

    /**
     * Sets the value of the changeReasonMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeReasonMemo(String value) {
        this.changeReasonMemo = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the businessEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityID() {
        return businessEntityID;
    }

    /**
     * Sets the value of the businessEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityID(String value) {
        this.businessEntityID = value;
    }

    /**
     * Gets the value of the patientDesigneeContactDetailTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDesigneContactDetailTypeName }
     *     
     */
    public PatientDesigneContactDetailTypeName getPatientDesigneeContactDetailTypeName() {
        return patientDesigneeContactDetailTypeName;
    }

    /**
     * Sets the value of the patientDesigneeContactDetailTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDesigneContactDetailTypeName }
     *     
     */
    public void setPatientDesigneeContactDetailTypeName(PatientDesigneContactDetailTypeName value) {
        this.patientDesigneeContactDetailTypeName = value;
    }

    /**
     * Gets the value of the contactRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactRelationship() {
        return contactRelationship;
    }

    /**
     * Sets the value of the contactRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactRelationship(String value) {
        this.contactRelationship = value;
    }

    /**
     * Gets the value of the patientDesigneeFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeFirstName() {
        return patientDesigneeFirstName;
    }

    /**
     * Sets the value of the patientDesigneeFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeFirstName(String value) {
        this.patientDesigneeFirstName = value;
    }

    /**
     * Gets the value of the patientDesigneeMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeMiddleName() {
        return patientDesigneeMiddleName;
    }

    /**
     * Sets the value of the patientDesigneeMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeMiddleName(String value) {
        this.patientDesigneeMiddleName = value;
    }

    /**
     * Gets the value of the patientDesigneeLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeLastName() {
        return patientDesigneeLastName;
    }

    /**
     * Sets the value of the patientDesigneeLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeLastName(String value) {
        this.patientDesigneeLastName = value;
    }

    /**
     * Gets the value of the patientDesigneeSuffixName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeSuffixName() {
        return patientDesigneeSuffixName;
    }

    /**
     * Sets the value of the patientDesigneeSuffixName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeSuffixName(String value) {
        this.patientDesigneeSuffixName = value;
    }

    /**
     * Gets the value of the patientDesigneeAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeAddressLine1() {
        return patientDesigneeAddressLine1;
    }

    /**
     * Sets the value of the patientDesigneeAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeAddressLine1(String value) {
        this.patientDesigneeAddressLine1 = value;
    }

    /**
     * Gets the value of the patientDesigneeAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeAddressLine2() {
        return patientDesigneeAddressLine2;
    }

    /**
     * Sets the value of the patientDesigneeAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeAddressLine2(String value) {
        this.patientDesigneeAddressLine2 = value;
    }

    /**
     * Gets the value of the patientDesigneeCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeCity() {
        return patientDesigneeCity;
    }

    /**
     * Sets the value of the patientDesigneeCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeCity(String value) {
        this.patientDesigneeCity = value;
    }

    /**
     * Gets the value of the patientDesigneeState property.
     * 
     * @return
     *     possible object is
     *     {@link StateCode }
     *     
     */
    public StateCode getPatientDesigneeState() {
        return patientDesigneeState;
    }

    /**
     * Sets the value of the patientDesigneeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateCode }
     *     
     */
    public void setPatientDesigneeState(StateCode value) {
        this.patientDesigneeState = value;
    }

    /**
     * Gets the value of the patientDesigneePostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneePostalCode() {
        return patientDesigneePostalCode;
    }

    /**
     * Sets the value of the patientDesigneePostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneePostalCode(String value) {
        this.patientDesigneePostalCode = value;
    }

    /**
     * Gets the value of the patientDesigneeZip4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeZip4() {
        return patientDesigneeZip4;
    }

    /**
     * Sets the value of the patientDesigneeZip4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeZip4(String value) {
        this.patientDesigneeZip4 = value;
    }

    /**
     * Gets the value of the patientDesigneeHomePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeHomePhone() {
        return patientDesigneeHomePhone;
    }

    /**
     * Sets the value of the patientDesigneeHomePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeHomePhone(String value) {
        this.patientDesigneeHomePhone = value;
    }

    /**
     * Gets the value of the patientDesigneeWorkPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeWorkPhone() {
        return patientDesigneeWorkPhone;
    }

    /**
     * Sets the value of the patientDesigneeWorkPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeWorkPhone(String value) {
        this.patientDesigneeWorkPhone = value;
    }

    /**
     * Gets the value of the patientDesigneeMobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeMobilePhone() {
        return patientDesigneeMobilePhone;
    }

    /**
     * Sets the value of the patientDesigneeMobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeMobilePhone(String value) {
        this.patientDesigneeMobilePhone = value;
    }

    /**
     * Gets the value of the patientDesigneePhoneOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneePhoneOther() {
        return patientDesigneePhoneOther;
    }

    /**
     * Sets the value of the patientDesigneePhoneOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneePhoneOther(String value) {
        this.patientDesigneePhoneOther = value;
    }

    /**
     * Gets the value of the patientDesigneePhoneOther1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneePhoneOther1() {
        return patientDesigneePhoneOther1;
    }

    /**
     * Sets the value of the patientDesigneePhoneOther1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneePhoneOther1(String value) {
        this.patientDesigneePhoneOther1 = value;
    }

    /**
     * Gets the value of the patientDesigneeFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeFax() {
        return patientDesigneeFax;
    }

    /**
     * Sets the value of the patientDesigneeFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeFax(String value) {
        this.patientDesigneeFax = value;
    }

    /**
     * Gets the value of the patientDesigneeEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeEmail() {
        return patientDesigneeEmail;
    }

    /**
     * Sets the value of the patientDesigneeEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeEmail(String value) {
        this.patientDesigneeEmail = value;
    }

    /**
     * Gets the value of the patientDesigneeEmailOther1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeEmailOther1() {
        return patientDesigneeEmailOther1;
    }

    /**
     * Sets the value of the patientDesigneeEmailOther1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeEmailOther1(String value) {
        this.patientDesigneeEmailOther1 = value;
    }

    /**
     * Gets the value of the patientDesigneeEmailOther2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeEmailOther2() {
        return patientDesigneeEmailOther2;
    }

    /**
     * Sets the value of the patientDesigneeEmailOther2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeEmailOther2(String value) {
        this.patientDesigneeEmailOther2 = value;
    }

    /**
     * Gets the value of the patientDesigneeEmailOther3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientDesigneeEmailOther3() {
        return patientDesigneeEmailOther3;
    }

    /**
     * Sets the value of the patientDesigneeEmailOther3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientDesigneeEmailOther3(String value) {
        this.patientDesigneeEmailOther3 = value;
    }

}
