//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


package com.sandata.lab.rest.oracle.model;

import com.sandata.lab.data.model.*;
import com.google.gson.annotations.SerializedName;
import com.sandata.lab.data.model.base.BaseObject;
import com.sandata.lab.data.model.dl.annotation.Mapping;
import com.sandata.lab.data.model.dl.annotation.OracleMetadata;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Payroll Input table holds information that is recieved from the payroll vendor about staff payroll
 * 
 * <p>Java class for Payroll_Input complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payroll_Input">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Payroll_Input_Earning_Detail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Payroll_Input_Tax_Detail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Payroll_Input_Deduction_Detail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Payroll_Input_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Payroll_Input_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Effective_Timestamp" use="required" type="{}Record_Effective_Timestamp" />
 *       &lt;attribute name="Record_Termination_Timestamp" use="required" type="{}Record_Termination_Timestamp" />
 *       &lt;attribute name="Record_Created_By" type="{}Record_Created_By" />
 *       &lt;attribute name="Record_Updated_By" type="{}Record_Updated_By" />
 *       &lt;attribute name="Change_Reason_Memo" type="{}Change_Reason_Memo" />
 *       &lt;attribute name="Current_Record_Indicator" use="required" type="{}Current_Record_Indicator" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Staff_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Interface_ID" use="required" type="{}Interface_ID" />
 *       &lt;attribute name="Week_End_Date" type="{}Week_End_Date" />
 *       &lt;attribute name="Net_Pay_Amount" type="{}Money" />
 *       &lt;attribute name="Gross_Pay_Amount" type="{}Money" />
 *       &lt;attribute name="Check_Number" type="{}ID" />
 *       &lt;attribute name="Check_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Check_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Electronic_Funds_Transfer_Transaction_Identifier" type="{}ID" />
 *       &lt;attribute name="Bank_Routing_Number" type="{}ID" />
 *       &lt;attribute name="Bank_Account_Number" type="{}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payroll_Input", propOrder = {
    "payrollInputEarningDetail",
    "payrollInputTaxDetail",
    "payrollInputDeductionDetail"
})
@OracleMetadata(
        packageName = "PKG_PAYROLL",
        insertMethod = "insertPrInput",
        updateMethod = "updatePrInput",
        deleteMethod = "deletePrInput",
        getMethod = "getPrInput",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.PrInputT",
        primaryKeys = {})
public class PayrollInput extends BaseObject {

	private static final long serialVersionUID = 1L;

    @XmlElement(name = "Payroll_Input_Earning_Detail")
    @SerializedName("PayrollInputEarningDetail")
    protected List<PayrollInputEarningDetail> payrollInputEarningDetail;
    @XmlElement(name = "Payroll_Input_Tax_Detail")
    @SerializedName("PayrollInputTaxDetail")
    protected List<PayrollInputTaxDetail> payrollInputTaxDetail;
    @XmlElement(name = "Payroll_Input_Deduction_Detail")
    @SerializedName("PayrollInputDeductionDetail")
    protected List<PayrollInputDeductionDetail> payrollInputDeductionDetail;
    @XmlAttribute(name = "Payroll_Input_SK", required = true)
    @SerializedName("PayrollInputSK")
	@Mapping(getter = "getPrInputSk", setter = "setPrInputSk", type = "java.math.BigDecimal", index = 0)
    protected BigInteger payrollInputSK;
    @XmlAttribute(name = "Payroll_Input_ID", required = true)
    @SerializedName("PayrollInputID")
	@Mapping(getter = "getPrInputId", setter = "setPrInputId", type = "String", index = 1)
    protected String payrollInputID;
    @XmlAttribute(name = "Record_Create_Timestamp", required = true)
    @SerializedName("RecordCreateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = 2)
    protected Date recordCreateTimestamp;
    @XmlAttribute(name = "Record_Update_Timestamp", required = true)
    @SerializedName("RecordUpdateTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = 3)
    protected Date recordUpdateTimestamp;
    @XmlAttribute(name = "Record_Effective_Timestamp", required = true)
    @SerializedName("RecordEffectiveTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecEffTmstp", setter = "setRecEffTmstp", type = "java.sql.Timestamp", index = 4)
    protected Date recordEffectiveTimestamp;
    @XmlAttribute(name = "Record_Termination_Timestamp", required = true)
    @SerializedName("RecordTerminationTimestamp")
    @XmlJavaTypeAdapter(Adapter1 .class)
	@Mapping(getter = "getRecTermTmstp", setter = "setRecTermTmstp", type = "java.sql.Timestamp", index = 5)
    protected Date recordTerminationTimestamp;
    @XmlAttribute(name = "Record_Created_By")
    @SerializedName("RecordCreatedBy")
	@Mapping(getter = "getRecCreatedBy", setter = "setRecCreatedBy", type = "String", index = 6)
    protected String recordCreatedBy;
    @XmlAttribute(name = "Record_Updated_By")
    @SerializedName("RecordUpdatedBy")
	@Mapping(getter = "getRecUpdatedBy", setter = "setRecUpdatedBy", type = "String", index = 7)
    protected String recordUpdatedBy;
    @XmlAttribute(name = "Change_Reason_Memo")
    @SerializedName("ChangeReasonMemo")
	@Mapping(getter = "getChangeReasonMemo", setter = "setChangeReasonMemo", type = "String", index = 8)
    protected String changeReasonMemo;
    @XmlAttribute(name = "Current_Record_Indicator", required = true)
    @SerializedName("CurrentRecordIndicator")
	@Mapping(getter = "getCurrRecInd", setter = "setCurrRecInd", type = "java.math.BigDecimal", index = 9)
    protected boolean currentRecordIndicator;
    @XmlAttribute(name = "Change_Version_ID", required = true)
    @SerializedName("ChangeVersionID")
	@Mapping(getter = "getChangeVersionId", setter = "setChangeVersionId", type = "java.math.BigDecimal", index = 10)
    protected BigInteger changeVersionID;
    @XmlAttribute(name = "Business_Entity_ID", required = true)
    @SerializedName("BusinessEntityID")
	@Mapping(getter = "getBeId", setter = "setBeId", type = "String", index = 11)
    protected String businessEntityID;
    @XmlAttribute(name = "Staff_ID", required = true)
    @SerializedName("StaffID")
	@Mapping(getter = "getStaffId", setter = "setStaffId", type = "String", index = 12)
    protected String staffID;
    @XmlAttribute(name = "Interface_ID", required = true)
    @SerializedName("InterfaceID")
	@Mapping(getter = "getIntfId", setter = "setIntfId", type = "String", index = 13)
    protected String interfaceID;
    @XmlAttribute(name = "Week_End_Date")
    @SerializedName("WeekEndDate")
    @XmlJavaTypeAdapter(Adapter2 .class)
	@Mapping(getter = "getWeekEndDate", setter = "setWeekEndDate", type = "java.sql.Timestamp", index = 14)
    protected Date weekEndDate;
    @XmlAttribute(name = "Net_Pay_Amount")
    @SerializedName("NetPayAmount")
	@Mapping(getter = "getNetPayAmt", setter = "setNetPayAmt", type = "java.math.BigDecimal", index = 15)
    protected BigDecimal netPayAmount;
    @XmlAttribute(name = "Gross_Pay_Amount")
    @SerializedName("GrossPayAmount")
	@Mapping(getter = "getGrossPayAmt", setter = "setGrossPayAmt", type = "java.math.BigDecimal", index = 16)
    protected BigDecimal grossPayAmount;
    @XmlAttribute(name = "Check_Number")
    @SerializedName("CheckNumber")
	@Mapping(getter = "getCheckNum", setter = "setCheckNum", type = "String", index = 17)
    protected String checkNumber;
    @XmlAttribute(name = "Check_Date")
    @SerializedName("CheckDate")
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
	@Mapping(getter = "getCheckDate", setter = "setCheckDate", type = "java.sql.Timestamp", index = 18)
    protected Date checkDate;
    @XmlAttribute(name = "Check_Indicator")
    @SerializedName("CheckIndicator")
	@Mapping(getter = "getCheckInd", setter = "setCheckInd", type = "java.math.BigDecimal", index = 19)
    protected Boolean checkIndicator;
    @XmlAttribute(name = "Electronic_Funds_Transfer_Transaction_Identifier")
    @SerializedName("ElectronicFundsTransferTransactionIdentifier")
	@Mapping(getter = "getEftTxnId", setter = "setEftTxnId", type = "String", index = 20)
    protected String electronicFundsTransferTransactionIdentifier;
    @XmlAttribute(name = "Bank_Routing_Number")
    @SerializedName("BankRoutingNumber")
	@Mapping(getter = "getBankRoutingNum", setter = "setBankRoutingNum", type = "String", index = 21)
    protected String bankRoutingNumber;
    @XmlAttribute(name = "Bank_Account_Number")
    @SerializedName("BankAccountNumber")
	@Mapping(getter = "getBankAccountNum", setter = "setBankAccountNum", type = "String", index = 22)
    protected String bankAccountNumber;

    /**
     * Gets the value of the payrollInputEarningDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payrollInputEarningDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayrollInputEarningDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayrollInputEarningDetail }
     * 
     * 
     */
    public List<PayrollInputEarningDetail> getPayrollInputEarningDetail() {
        if (payrollInputEarningDetail == null) {
            payrollInputEarningDetail = new ArrayList<PayrollInputEarningDetail>();
        }
        return this.payrollInputEarningDetail;
    }

    /**
     * Gets the value of the payrollInputTaxDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payrollInputTaxDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayrollInputTaxDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayrollInputTaxDetail }
     * 
     * 
     */
    public List<PayrollInputTaxDetail> getPayrollInputTaxDetail() {
        if (payrollInputTaxDetail == null) {
            payrollInputTaxDetail = new ArrayList<PayrollInputTaxDetail>();
        }
        return this.payrollInputTaxDetail;
    }

    /**
     * Gets the value of the payrollInputDeductionDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payrollInputDeductionDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayrollInputDeductionDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayrollInputDeductionDetail }
     * 
     * 
     */
    public List<PayrollInputDeductionDetail> getPayrollInputDeductionDetail() {
        if (payrollInputDeductionDetail == null) {
            payrollInputDeductionDetail = new ArrayList<PayrollInputDeductionDetail>();
        }
        return this.payrollInputDeductionDetail;
    }

    /**
     * Gets the value of the payrollInputSK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayrollInputSK() {
        return payrollInputSK;
    }

    /**
     * Sets the value of the payrollInputSK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayrollInputSK(BigInteger value) {
        this.payrollInputSK = value;
    }

    /**
     * Gets the value of the payrollInputID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayrollInputID() {
        return payrollInputID;
    }

    /**
     * Sets the value of the payrollInputID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayrollInputID(String value) {
        this.payrollInputID = value;
    }

    /**
     * Gets the value of the recordCreateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordCreateTimestamp() {
        return recordCreateTimestamp;
    }

    /**
     * Sets the value of the recordCreateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreateTimestamp(Date value) {
        this.recordCreateTimestamp = value;
    }

    /**
     * Gets the value of the recordUpdateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordUpdateTimestamp() {
        return recordUpdateTimestamp;
    }

    /**
     * Sets the value of the recordUpdateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateTimestamp(Date value) {
        this.recordUpdateTimestamp = value;
    }

    /**
     * Gets the value of the recordEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordEffectiveTimestamp() {
        return recordEffectiveTimestamp;
    }

    /**
     * Sets the value of the recordEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordEffectiveTimestamp(Date value) {
        this.recordEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the recordTerminationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getRecordTerminationTimestamp() {
        return recordTerminationTimestamp;
    }

    /**
     * Sets the value of the recordTerminationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordTerminationTimestamp(Date value) {
        this.recordTerminationTimestamp = value;
    }

    /**
     * Gets the value of the recordCreatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreatedBy() {
        return recordCreatedBy;
    }

    /**
     * Sets the value of the recordCreatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreatedBy(String value) {
        this.recordCreatedBy = value;
    }

    /**
     * Gets the value of the recordUpdatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdatedBy() {
        return recordUpdatedBy;
    }

    /**
     * Sets the value of the recordUpdatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdatedBy(String value) {
        this.recordUpdatedBy = value;
    }

    /**
     * Gets the value of the changeReasonMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeReasonMemo() {
        return changeReasonMemo;
    }

    /**
     * Sets the value of the changeReasonMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeReasonMemo(String value) {
        this.changeReasonMemo = value;
    }

    /**
     * Gets the value of the currentRecordIndicator property.
     * 
     */
    public boolean isCurrentRecordIndicator() {
        return currentRecordIndicator;
    }

    /**
     * Sets the value of the currentRecordIndicator property.
     * 
     */
    public void setCurrentRecordIndicator(boolean value) {
        this.currentRecordIndicator = value;
    }

    /**
     * Gets the value of the changeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeVersionID() {
        return changeVersionID;
    }

    /**
     * Sets the value of the changeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeVersionID(BigInteger value) {
        this.changeVersionID = value;
    }

    /**
     * Gets the value of the businessEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessEntityID() {
        return businessEntityID;
    }

    /**
     * Sets the value of the businessEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessEntityID(String value) {
        this.businessEntityID = value;
    }

    /**
     * Gets the value of the staffID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffID() {
        return staffID;
    }

    /**
     * Sets the value of the staffID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffID(String value) {
        this.staffID = value;
    }

    /**
     * Gets the value of the interfaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceID() {
        return interfaceID;
    }

    /**
     * Sets the value of the interfaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceID(String value) {
        this.interfaceID = value;
    }

    /**
     * Gets the value of the weekEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getWeekEndDate() {
        return weekEndDate;
    }

    /**
     * Sets the value of the weekEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekEndDate(Date value) {
        this.weekEndDate = value;
    }

    /**
     * Gets the value of the netPayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPayAmount() {
        return netPayAmount;
    }

    /**
     * Sets the value of the netPayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPayAmount(BigDecimal value) {
        this.netPayAmount = value;
    }

    /**
     * Gets the value of the grossPayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPayAmount() {
        return grossPayAmount;
    }

    /**
     * Sets the value of the grossPayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPayAmount(BigDecimal value) {
        this.grossPayAmount = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckNumber(String value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the checkDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * Sets the value of the checkDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckDate(Date value) {
        this.checkDate = value;
    }

    /**
     * Gets the value of the checkIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckIndicator() {
        return checkIndicator;
    }

    /**
     * Sets the value of the checkIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckIndicator(Boolean value) {
        this.checkIndicator = value;
    }

    /**
     * Gets the value of the electronicFundsTransferTransactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicFundsTransferTransactionIdentifier() {
        return electronicFundsTransferTransactionIdentifier;
    }

    /**
     * Sets the value of the electronicFundsTransferTransactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicFundsTransferTransactionIdentifier(String value) {
        this.electronicFundsTransferTransactionIdentifier = value;
    }

    /**
     * Gets the value of the bankRoutingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankRoutingNumber() {
        return bankRoutingNumber;
    }

    /**
     * Sets the value of the bankRoutingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankRoutingNumber(String value) {
        this.bankRoutingNumber = value;
    }

    /**
     * Gets the value of the bankAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * Sets the value of the bankAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankAccountNumber(String value) {
        this.bankAccountNumber = value;
    }

}
