//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


using Sandata.George.Common;
using Sandata.George.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;





/**
 * Personnel working at an agency, who is not a field worker, rather a coordinator/supervisor, unit coordinator or manager.
 * 
 * <p>Java class for Administrative_Staff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Administrative_Staff">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Administrative_Staff_Relationship" type="{}Administrative_Staff_Relationship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Administrative_Staff_Role_Cross_Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Administrative_Staff_Staff_Crosswalk" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Administrative_Staff_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Effective_Timestamp" use="required" type="{}Record_Effective_Timestamp" />
 *       &lt;attribute name="Record_Termination_Timestamp" use="required" type="{}Record_Termination_Timestamp" />
 *       &lt;attribute name="Record_Created_By" type="{}Record_Created_By" />
 *       &lt;attribute name="Record_Updated_By" type="{}Record_Updated_By" />
 *       &lt;attribute name="Change_Reason_Memo" type="{}Change_Reason_Memo" />
 *       &lt;attribute name="Current_Record_Indicator" use="required" type="{}Current_Record_Indicator" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Business_Entity_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Administrative_Staff_ID" use="required" type="{}ID" />
 *       &lt;attribute name="Administrative_Staff_First_Name" type="{}Name_Generic" />
 *       &lt;attribute name="Administrative_Staff_Middle_Name" type="{}Name_Generic" />
 *       &lt;attribute name="Administrative_Staff_Last_Name" type="{}Name_Generic" />
 *       &lt;attribute name="Administrative_Staff_Date_Of_Birth" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Administrative_Staff_Home_Phone" type="{}Phone" />
 *       &lt;attribute name="Administrative_Staff_Mobile_Phone" type="{}Phone" />
 *       &lt;attribute name="Administrative_Staff_Address_Line_1" type="{}Address_Line" />
 *       &lt;attribute name="Administrative_Staff_Address_Line_2" type="{}Address_Line" />
 *       &lt;attribute name="Administrative_Staff_City" type="{}City" />
 *       &lt;attribute name="Administrative_Staff_State" type="{}State_Name" />
 *       &lt;attribute name="Administrative_Staff_Postal_Code" type="{}Postal_Code" />
 *       &lt;attribute name="Administrative_Staff_Zip4" type="{}Zip4" />
 *       &lt;attribute name="Administrative_Staff_Email_Address" type="{}Email" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
namespace Sandata.George.Domain.Entities
{
	[DataContract]
	public class AdministrativeStaff
	{

			[DataMember]
			public List<AdministrativeStaffRelationship> AdministrativeStaffRelationshipCollection { get; set; }

			[DataMember]
			public List<AdministrativeStaffRoleCrossReference> AdministrativeStaffRoleCrossReferenceCollection { get; set; }

			[DataMember]
			public List<AdministrativeStaffStaffCrosswalk> AdministrativeStaffStaffCrosswalkCollection { get; set; }

			[DataMember(IsRequired = true)]
			public long AdministrativeStaffSK { get; set; }

			[IgnoreDataMember]
			public DateTime RecordCreateTimestamp { get; set; }

			[DataMember(Name = "RecordCreateTimestamp", IsRequired = true)]
			public string RecordCreateTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordCreateTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordCreateTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[IgnoreDataMember]
			public DateTime RecordUpdateTimestamp { get; set; }

			[DataMember(Name = "RecordUpdateTimestamp", IsRequired = true)]
			public string RecordUpdateTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordUpdateTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordUpdateTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[IgnoreDataMember]
			public DateTime RecordEffectiveTimestamp { get; set; }

			[DataMember(Name = "RecordEffectiveTimestamp", IsRequired = true)]
			public string RecordEffectiveTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordEffectiveTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordEffectiveTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[IgnoreDataMember]
			public DateTime RecordTerminationTimestamp { get; set; }

			[DataMember(Name = "RecordTerminationTimestamp", IsRequired = true)]
			public string RecordTerminationTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordTerminationTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordTerminationTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String RecordCreatedBy { get; set; }

			[DataMember]
			public String RecordUpdatedBy { get; set; }

			[DataMember]
			public String ChangeReasonMemo { get; set; }

			[DataMember(IsRequired = true)]
			public bool CurrentRecordIndicator { get; set; }

			[DataMember(IsRequired = true)]
			public long ChangeVersionID { get; set; }

			[DataMember(IsRequired = true)]
			public String BusinessEntityID { get; set; }

			[DataMember(IsRequired = true)]
			public String AdministrativeStaffID { get; set; }

			[DataMember]
			public String AdministrativeStaffFirstName { get; set; }

			[DataMember]
			public String AdministrativeStaffMiddleName { get; set; }

			[DataMember]
			public String AdministrativeStaffLastName { get; set; }

			[IgnoreDataMember]
			public Nullable<DateTime> AdministrativeStaffDateOfBirth { get; set; }

			[DataMember(Name = "AdministrativeStaffDateOfBirth")]
			public string AdministrativeStaffDateOfBirthStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(AdministrativeStaffDateOfBirth);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						AdministrativeStaffDateOfBirth = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String AdministrativeStaffHomePhone { get; set; }

			[DataMember]
			public String AdministrativeStaffMobilePhone { get; set; }

			[DataMember]
			public String AdministrativeStaffAddressLine1 { get; set; }

			[DataMember]
			public String AdministrativeStaffAddressLine2 { get; set; }

			[DataMember]
			public String AdministrativeStaffCity { get; set; }

			[DataMember]
			public String AdministrativeStaffState { get; set; }

			[DataMember]
			public String AdministrativeStaffPostalCode { get; set; }

			[DataMember]
			public String AdministrativeStaffZip4 { get; set; }

			[DataMember]
			public String AdministrativeStaffEmailAddress { get; set; }


	}
}
