//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 10:25:43 PM EDT 
//


using Sandata.George.Common;
using Sandata.George.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;











/**
 * Hierarchical data store for tenant configuration. Stores data as a key-value pairs.
 * 
 * <p>Java class for Application_Tenant_Key_Configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application_Tenant_Key_Configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Application_Tenant_Key_Configuration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Application_Tenant_Key_Configuration_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Application_Tenant_Key_Configuration_Parent_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Application_Tenant_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Key_Name" use="required" type="{}Key_Name" />
 *       &lt;attribute name="Tenant_Key_Configuration_Value" type="{}Key_Value" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@OracleMetadata(
        packageName = "PKG_APP",
        insertMethod = "insertAppTenantKeyConf",
        updateMethod = "updateAppTenantKeyConf",
        deleteMethod = "deleteAppTenantKeyConf",
        getMethod = "getAppTenantKeyConf",
        findMethod = "NotDefined_FindMethod",
        jpubClass = "com.sandata.lab.data.model.jpub.model.AppTenantKeyConfT",
        primaryKeys = {})
namespace Sandata.George.Domain.Entities
{
	[DataContract]
	public class ApplicationTenantKeyConfiguration
	{




			[DataMember]
			public List<ApplicationTenantKeyConfiguration> ApplicationTenantKeyConfigurationPropertyCollection { get; set; }

			[DataMember(IsRequired = true)]
			public = "getAppTenantKeyConfSk", setter = "setAppTenantKeyConfSk", type = "java.math.BigDecimal", index = ApplicationTenantKeyConfigurationSK { get; set; }

    protected BigInteger applicationTenantKeyConfigurationSK;
			[DataMember(IsRequired = true)]
			public = "getRecCreateTmstp", setter = "setRecCreateTmstp", type = "java.sql.Timestamp", index = RecordCreateTimestamp { get; set; }

    protected Date recordCreateTimestamp;
			[DataMember(IsRequired = true)]
			public = "getRecUpdateTmstp", setter = "setRecUpdateTmstp", type = "java.sql.Timestamp", index = RecordUpdateTimestamp { get; set; }

    protected Date recordUpdateTimestamp;
			[DataMember]
			public = "getAppTenantKeyConfParSk", setter = "setAppTenantKeyConfParSk", type = "java.math.BigDecimal", index = ApplicationTenantKeyConfigurationParentSK { get; set; }

    protected BigInteger applicationTenantKeyConfigurationParentSK;
			[DataMember(IsRequired = true)]
			public = "getAppTenantSk", setter = "setAppTenantSk", type = "java.math.BigDecimal", index = ApplicationTenantSK { get; set; }

    protected BigInteger applicationTenantSK;
			[DataMember(IsRequired = true)]
			public = "getKeyName", setter = "setKeyName", type = "String", index = KeyName { get; set; }

    protected String keyName;
			[DataMember]
			public = "getTenantKeyConfVal", setter = "setTenantKeyConfVal", type = "String", index = TenantKeyConfigurationValue { get; set; }

    protected String tenantKeyConfigurationValue;

	}
}
