//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.27 at 10:53:27 PM EST 
//


using Sandata.George.Common;
using Sandata.George.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;





/**
 * The Payment 835 table holds the specific payment records received on an 835 explanation of payment (EOP), and is used to reconcile payments to invoices and invoice details.
 * 
 * 
 * <p>Java class for Claim_Payment_Advice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Claim_Payment_Advice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Payment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Claim_Payment_Advice_Line" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Claim_Payment_Advice_SK" use="required" type="{}Surrogate_Key" />
 *       &lt;attribute name="Record_Create_Timestamp" use="required" type="{}Record_Create_Timestamp" />
 *       &lt;attribute name="Record_Update_Timestamp" use="required" type="{}Record_Update_Timestamp" />
 *       &lt;attribute name="Record_Created_By" type="{}Record_Created_By" />
 *       &lt;attribute name="Record_Updated_By" type="{}Record_Updated_By" />
 *       &lt;attribute name="Change_Version_ID" use="required" type="{}Change_Version_ID" />
 *       &lt;attribute name="Business_Entity_ID" type="{}ID" />
 *       &lt;attribute name="Billing_Detail_SK" type="{}Surrogate_Key" />
 *       &lt;attribute name="Electronic_Data_Interchange_Submitter_ID" type="{}ID" />
 *       &lt;attribute name="Electronic_Data_Interchange_Receiver_ID" type="{}ID" />
 *       &lt;attribute name="Claim_Payment_Advice_Control_Number">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="9"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Payer_ID" type="{}ID" />
 *       &lt;attribute name="Payer_Name" type="{}Name" />
 *       &lt;attribute name="Check_Number" type="{}ID" />
 *       &lt;attribute name="Check_Indicator" type="{}Indicator" />
 *       &lt;attribute name="Check_Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Electronic_Funds_Transfer_Transaction_Identifier" type="{}ID" />
 *       &lt;attribute name="Payment_Amount" type="{}Money" />
 *       &lt;attribute name="Provider_ID" type="{}ID" />
 *       &lt;attribute name="Provider_ID_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Provider_Name" type="{}Name_Generic" />
 *       &lt;attribute name="Provider_Address_Line_1" type="{}Address_Line" />
 *       &lt;attribute name="Provider_Address_Line_2" type="{}Address_Line" />
 *       &lt;attribute name="Provider_City" type="{}City" />
 *       &lt;attribute name="Provider_State" type="{}State_Name" />
 *       &lt;attribute name="Provider_Postal_Code" type="{}Postal_Code" />
 *       &lt;attribute name="Provider_ID_Other">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Provider_ID_Other_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Invoice_Number" type="{}ID" />
 *       &lt;attribute name="Payer_Claim_Status_Code">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Charge_Total_Amount" type="{}Money" />
 *       &lt;attribute name="Claim_Payment_Total_Amount" type="{}Money" />
 *       &lt;attribute name="Claim_Patient_Responsibility_Amount" type="{}Money" />
 *       &lt;attribute name="Claim_Reference_Number">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Facility_Type_Code">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Invoice_Submission_Type_Code" type="{}Invoice_Submission_Type_Code" />
 *       &lt;attribute name="Claim_Entity_Name_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Entity_First_Name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Entity_Last_Name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Entity_ID_Type_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Entity_ID_Number" type="{}ID" />
 *       &lt;attribute name="Claim_Start_Date" use="required" type="{}Attribute_Start_Date" />
 *       &lt;attribute name="Claim_Start_Date_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_End_Date" use="required" type="{}Attribute_End_Date" />
 *       &lt;attribute name="Claim_End_Date_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Amount_Qualifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="50"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Claim_Amount" type="{}Money" />
 *       &lt;attribute name="Prepaid_Capitation_Plan_Code" type="{}Code" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
namespace Sandata.George.Domain.Entities
{
	[DataContract]
	public class ClaimPaymentAdvice
	{

			[DataMember]
			public List<Payment> PaymentPropertyCollection { get; set; }

			[DataMember]
			public List<ClaimPaymentAdviceLine> ClaimPaymentAdviceLineCollection { get; set; }

			[DataMember(IsRequired = true)]
			public long ClaimPaymentAdviceSK { get; set; }

			[IgnoreDataMember]
			public DateTime RecordCreateTimestamp { get; set; }

			[DataMember(Name = "RecordCreateTimestamp", IsRequired = true)]
			public string RecordCreateTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordCreateTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordCreateTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[IgnoreDataMember]
			public DateTime RecordUpdateTimestamp { get; set; }

			[DataMember(Name = "RecordUpdateTimestamp", IsRequired = true)]
			public string RecordUpdateTimestampStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(RecordUpdateTimestamp);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						RecordUpdateTimestamp = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String RecordCreatedBy { get; set; }

			[DataMember]
			public String RecordUpdatedBy { get; set; }

			[DataMember(IsRequired = true)]
			public long ChangeVersionID { get; set; }

			[DataMember]
			public String BusinessEntityID { get; set; }

			[DataMember]
			public long? BillingDetailSK { get; set; }

			[DataMember]
			public String ElectronicDataInterchangeSubmitterID { get; set; }

			[DataMember]
			public String ElectronicDataInterchangeReceiverID { get; set; }

			[DataMember]
			public String ClaimPaymentAdviceControlNumber { get; set; }

			[DataMember]
			public String PayerID { get; set; }

			[DataMember]
			public String PayerName { get; set; }

			[DataMember]
			public String CheckNumber { get; set; }

			[DataMember]
			public bool? CheckIndicator { get; set; }

			[IgnoreDataMember]
			public Nullable<DateTime> CheckDate { get; set; }

			[DataMember(Name = "CheckDate")]
			public string CheckDateStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(CheckDate);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						CheckDate = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String ElectronicFundsTransferTransactionIdentifier { get; set; }

			[DataMember]
			public decimal? PaymentAmount { get; set; }

			[DataMember]
			public String ProviderID { get; set; }

			[DataMember]
			public String ProviderIDQualifier { get; set; }

			[DataMember]
			public String ProviderName { get; set; }

			[DataMember]
			public String ProviderAddressLine1 { get; set; }

			[DataMember]
			public String ProviderAddressLine2 { get; set; }

			[DataMember]
			public String ProviderCity { get; set; }

			[DataMember]
			public String ProviderState { get; set; }

			[DataMember]
			public String ProviderPostalCode { get; set; }

			[DataMember]
			public String ProviderIDOther { get; set; }

			[DataMember]
			public String ProviderIDOtherQualifier { get; set; }

			[DataMember]
			public String InvoiceNumber { get; set; }

			[DataMember]
			public String PayerClaimStatusCode { get; set; }

			[DataMember]
			public decimal? ClaimChargeTotalAmount { get; set; }

			[DataMember]
			public decimal? ClaimPaymentTotalAmount { get; set; }

			[DataMember]
			public decimal? ClaimPatientResponsibilityAmount { get; set; }

			[DataMember]
			public String ClaimReferenceNumber { get; set; }

			[DataMember]
			public String ClaimFacilityTypeCode { get; set; }

			[DataMember]
			public String InvoiceSubmissionTypeCode { get; set; }

			[DataMember]
			public String ClaimEntityNameQualifier { get; set; }

			[DataMember]
			public String ClaimEntityFirstName { get; set; }

			[DataMember]
			public String ClaimEntityLastName { get; set; }

			[DataMember]
			public String ClaimEntityIDTypeQualifier { get; set; }

			[DataMember]
			public String ClaimEntityIDNumber { get; set; }

			[IgnoreDataMember]
			public DateTime ClaimStartDate { get; set; }

			[DataMember(Name = "ClaimStartDate", IsRequired = true)]
			public string ClaimStartDateStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(ClaimStartDate);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						ClaimStartDate = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String ClaimStartDateQualifier { get; set; }

			[IgnoreDataMember]
			public DateTime ClaimEndDate { get; set; }

			[DataMember(Name = "ClaimEndDate", IsRequired = true)]
			public string ClaimEndDateStr
			{
				get
				{
					return DateTimeHelper.ToDateTimeString(ClaimEndDate);
				}
				set
				{
					if (!String.IsNullOrEmpty(value))
					{
						ClaimEndDate = DateTimeHelper.ToDateTime(value);
					}
				}
			}

			[DataMember]
			public String ClaimEndDateQualifier { get; set; }

			[DataMember]
			public String ClaimAmountQualifier { get; set; }

			[DataMember]
			public decimal? ClaimAmount { get; set; }

			[DataMember]
			public String PrepaidCapitationPlanCode { get; set; }


	}
}
