SELECT * FROM (SELECT ROWNUM ROW_NUMBER, COUNT(*) OVER() TOTAL_ROWS, R1.* FROM (

  SELECT * FROM (

      (SELECT * FROM CONTR
        WHERE PAYER_ID IN ('0002744')
          AND (TO_CHAR(REC_TERM_TMSTP, 'YYYY-MM-DD') = '9999-12-31' AND CURR_REC_IND = 1)
          AND CAST(SYS_EXTRACT_UTC(CURRENT_TIMESTAMP) AS DATE)
                BETWEEN CONTR_EFF_DATE AND CONTR_TERM_DATE
        ORDER BY CONTR_CONT_NAME ASC
    )
  )

) R1)

WHERE ROW_NUMBER BETWEEN 1 AND 10;
