SELECT T1.BE_ID, T2.TENANT_KEY_CONF_VAL FROM APP_TENANT_BE_XWALK T1
  INNER JOIN APP_TENANT_KEY_CONF T2
    ON T1.APP_TENANT_SK=T2.APP_TENANT_SK
 WHERE T1.BE_ID='1'
  AND T2.KEY_NAME='AGNCY_MGMT_PAT_STAFF_VIS_VER';
